export enum BillVersionEnum {
	IH = 'Introduced',
	IS = 'Introduced',
	RFH = 'Referred',
	RFS = 'Referred',
	RDS = 'Received',
	RHS = 'Received',
	RCS = 'Reference Change',
	RCH = 'Reference Change',
	RS = 'Reported',
	RH = 'Reported',
	PCS = 'Placed on Calendar',
	PCH = 'Placed on Calendar',
	CPS = 'Considered and Passed',
	CPH = 'Considered and Passed',
	EAS = 'Engrossed Amendment',
	EAH = 'Engrossed Amendment',
	ES = 'Engrossed',
	EH = 'Engrossed',
	RAS = 'Referred w/Amendments',
	RAH = 'Referred w/Amendments',
	ENR = 'Enrolled',
}
