"""empty message

Revision ID: 581b84b38238
Revises: ea85413bf51b
Create Date: 2025-05-27 01:36:37.605075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '581b84b38238'
down_revision: Union[str, None] = 'ea85413bf51b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legislation_committee', sa.Column('committee_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_legislation_committee_committee_id'), 'legislation_committee', ['committee_id'], unique=False)
    op.drop_column('legislation_committee', 'house_committee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legislation_committee', sa.Column('house_committee_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_legislation_committee_committee_id'), table_name='legislation_committee')
    op.drop_column('legislation_committee', 'committee_id')
    # ### end Alembic commands ###
