"""Add legis action

Revision ID: 92a7b9f03f89
Revises: 8da0e1e71536
Create Date: 2025-03-09 17:18:17.449709

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "92a7b9f03f89"
down_revision: Union[str, None] = "8da0e1e71536"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legislation_action",
        sa.Column("legislation_action_id", sa.Integer(), nullable=False),
        sa.Column("legislation_id", sa.Integer(), nullable=True),
        sa.Column("action_date", sa.Date(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("action_type", sa.String(), nullable=True),
        sa.Column("action_code", sa.String(), nullable=True),
        sa.Column("source_code", sa.String(), nullable=True),
        sa.Column("source_name", sa.String(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["legislation_id"], ["legislation.legislation_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("legislation_action_id"),
    )
    op.create_index(
        op.f("ix_legislation_action_legislation_id"),
        "legislation_action",
        ["legislation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_legislation_action_legislation_id"), table_name="legislation_action"
    )
    op.drop_table("legislation_action")
    # ### end Alembic commands ###
