"""votes-datetime

Revision ID: b3b426df69a6
Revises: c54322bdb307
Create Date: 2025-01-19 02:52:36.012847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b426df69a6'
down_revision: Union[str, None] = 'c54322bdb307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legislation_vote', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.drop_column('legislation_vote', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legislation_vote', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('legislation_vote', 'datetime')
    # ### end Alembic commands ###
