"""empty message

Revision ID: bc4ec35d0874
Revises: 92a7b9f03f89
Create Date: 2025-05-04 16:12:32.507433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4ec35d0874'
down_revision: Union[str, None] = '92a7b9f03f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appropriation', 'prompt_batch_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='appropriations')
    op.add_column('prompt', sa.Column('model', sa.String(), nullable=False), schema='prompts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt', 'model', schema='prompts')
    op.alter_column('appropriation', 'prompt_batch_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='appropriations')
    # ### end Alembic commands ###
