"""empty message

Revision ID: bf2269ea67a1
Revises: a3b78ac73761
Create Date: 2024-12-29 14:56:23.864218

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy import Text
import congress_parser

# revision identifiers, used by Alembic.
revision: str = "bf2269ea67a1"
down_revision: Union[str, None] = "a3b78ac73761"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "legislation_action_parse",
        sa.Column("legislation_action_parse_id", sa.Integer(), nullable=False),
        sa.Column("legislation_version_id", sa.Integer(), nullable=True),
        sa.Column("legislation_content_id", sa.Integer(), nullable=True),
        sa.Column(
            "actions",
            congress_db.models.CastingArray(JSONB(astext_type=Text())),
            nullable=True,
        ),
        sa.Column(
            "citations",
            congress_db.models.CastingArray(JSONB(astext_type=Text())),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["legislation_content_id"],
            ["legislation_content.legislation_content_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["legislation_version_id"],
            ["legislation_version.legislation_version_id"],
        ),
        sa.PrimaryKeyConstraint("legislation_action_parse_id"),
    )
    op.create_index(
        op.f("ix_legislation_action_parse_legislation_content_id"),
        "legislation_action_parse",
        ["legislation_content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legislation_action_parse_legislation_version_id"),
        "legislation_action_parse",
        ["legislation_version_id"],
        unique=False,
    )
    op.drop_column("legislation_content", "action_parse")

    op.add_column(
        "legislator",
        sa.Column(
            "image_url",
            sa.String(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "legislator",
        sa.Column(
            "image_source",
            sa.String(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "legislator",
        sa.Column(
            "profile",
            sa.String(),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("legislator", "profile")
    op.drop_column("legislator", "image_source")
    op.drop_column("legislator", "image_url")

    op.add_column(
        "legislation_content",
        sa.Column(
            "action_parse",
            postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(
        op.f("ix_legislation_action_parse_legislation_version_id"),
        table_name="legislation_action_parse",
    )
    op.drop_index(
        op.f("ix_legislation_action_parse_legislation_content_id"),
        table_name="legislation_action_parse",
    )
    op.drop_table("legislation_action_parse")
    # ### end Alembic commands ###
