"""votes-metadata


Revision ID: c54322bdb307
Revises: 79a29914ef4a
Create Date: 2025-01-19 00:40:01.827121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54322bdb307'
down_revision: Union[str, None] = '79a29914ef4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legislation_vote', sa.Column('chamber', sa.Enum('House', 'Senate', name='legislationchamber'), nullable=True))
    op.add_column('legislation_vote', sa.Column('congress_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_legislation_vote_congress_id'), 'legislation_vote', ['congress_id'], unique=False)
    op.create_foreign_key(None, 'legislation_vote', 'congress', ['congress_id'], ['congress_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'legislation_vote', type_='foreignkey')
    op.drop_index(op.f('ix_legislation_vote_congress_id'), table_name='legislation_vote')
    op.drop_column('legislation_vote', 'congress_id')
    op.drop_column('legislation_vote', 'chamber')
    # ### end Alembic commands ###
