"""empty message

Revision ID: ea85413bf51b
Revises: bc4ec35d0874
Create Date: 2025-05-26 02:15:42.196842

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ea85413bf51b"
down_revision: Union[str, None] = "bc4ec35d0874"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "legislation_committee", sa.Column("congress_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "legislation_committee", sa.Column("thomas_id", sa.String(), nullable=True)
    )
    op.add_column(
        "legislation_committee", sa.Column("parent_id", sa.Integer(), nullable=True)
    )
    op.add_column("legislation_committee", sa.Column("url", sa.String(), nullable=True))
    op.add_column(
        "legislation_committee", sa.Column("minority_url", sa.String(), nullable=True)
    )
    op.add_column(
        "legislation_committee",
        sa.Column("house_committee_id", sa.String(), nullable=True),
    )
    op.add_column(
        "legislation_committee", sa.Column("address", sa.String(), nullable=True)
    )
    op.add_column(
        "legislation_committee", sa.Column("phone", sa.String(), nullable=True)
    )
    op.add_column(
        "legislation_committee", sa.Column("rss_url", sa.String(), nullable=True)
    )
    op.add_column(
        "legislation_committee", sa.Column("jurisdiction", sa.String(), nullable=True)
    )
    op.add_column(
        "legislation_committee", sa.Column("youtube_id", sa.String(), nullable=True)
    )
    op.drop_index(
        "ix_legislation_committee_subcommittee", table_name="legislation_committee"
    )
    op.create_index(
        op.f("ix_legislation_committee_congress_id"),
        "legislation_committee",
        ["congress_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legislation_committee_parent_id"),
        "legislation_committee",
        ["parent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legislation_committee_thomas_id"),
        "legislation_committee",
        ["thomas_id"],
        unique=False,
    )
    op.drop_constraint(
        "legislation_committee_subcommittee_fkey",
        "legislation_committee",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "legislation_committee",
        "congress",
        ["congress_id"],
        ["congress_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "legislation_committee",
        "legislation_committee",
        ["parent_id"],
        ["legislation_committee_id"],
        ondelete="CASCADE",
    )
    op.drop_column("legislation_committee", "subcommittee")
    op.alter_column(
        "appropriation",
        "prompt_batch_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        schema="appropriations",
    )
    op.alter_column(
        "prompt", "model", existing_type=sa.VARCHAR(), nullable=False, schema="prompts"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "prompt", "model", existing_type=sa.VARCHAR(), nullable=True, schema="prompts"
    )
    op.alter_column(
        "appropriation",
        "prompt_batch_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        schema="appropriations",
    )
    op.add_column(
        "legislation_committee",
        sa.Column("subcommittee", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "legislation_committee", type_="foreignkey")
    op.drop_constraint(None, "legislation_committee", type_="foreignkey")
    op.create_foreign_key(
        "legislation_committee_subcommittee_fkey",
        "legislation_committee",
        "legislation_committee",
        ["subcommittee"],
        ["legislation_committee_id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_legislation_committee_thomas_id"), table_name="legislation_committee"
    )
    op.drop_index(
        op.f("ix_legislation_committee_parent_id"), table_name="legislation_committee"
    )
    op.drop_index(
        op.f("ix_legislation_committee_congress_id"), table_name="legislation_committee"
    )
    op.create_index(
        "ix_legislation_committee_subcommittee",
        "legislation_committee",
        ["subcommittee"],
        unique=False,
    )
    op.drop_column("legislation_committee", "youtube_id")
    op.drop_column("legislation_committee", "jurisdiction")
    op.drop_column("legislation_committee", "rss_url")
    op.drop_column("legislation_committee", "phone")
    op.drop_column("legislation_committee", "address")
    op.drop_column("legislation_committee", "house_committee_id")
    op.drop_column("legislation_committee", "minority_url")
    op.drop_column("legislation_committee", "url")
    op.drop_column("legislation_committee", "parent_id")
    op.drop_column("legislation_committee", "thomas_id")
    op.drop_column("legislation_committee", "congress_id")
    # ### end Alembic commands ###
