"""Auth schema and nullable fix

Revision ID: f141b3473b1f
Revises: 581b84b38238
Create Date: 2025-12-28 03:48:52.739262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f141b3473b1f'
down_revision: Union[str, None] = '581b84b38238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS authentication")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_verified', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='authentication'
    )
    op.create_table('verification_token',
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identifier', 'token'),
    sa.UniqueConstraint('identifier', 'token', name='verification_token_pk'),
    schema='authentication'
    )
    op.create_table('account',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_account_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('id_token', sa.String(), nullable=True),
    sa.Column('session_state', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['authentication.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider', 'provider_account_id'),
    sa.UniqueConstraint('provider', 'provider_account_id', name='account_pk'),
    schema='authentication'
    )
    op.create_table('session',
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['authentication.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_token'),
    sa.UniqueConstraint('session_token'),
    schema='authentication'
    )
    op.alter_column('legislation_committee', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usc_content_diff', 'usc_content_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usc_content_diff', 'usc_section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usc_content_diff', 'usc_chapter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP SCHEMA IF EXISTS authentication CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usc_content_diff', 'usc_chapter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usc_content_diff', 'usc_section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usc_content_diff', 'usc_content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('legislation_committee', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('session', schema='authentication')
    op.drop_table('account', schema='authentication')
    op.drop_table('verification_token', schema='authentication')
    op.drop_table('user', schema='authentication')
    # ### end Alembic commands ###
