# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from congress_api.models.base_model_ import Model
from congress_api.models.bill_diff_metadata_item import BillDiffMetadataItem
from congress_api import util

from congress_api.models.bill_diff_metadata_item import BillDiffMetadataItem  # noqa: E501

class BillDiffList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, legislation_version_id=None, sections=None, short_title=None, long_title=None):  # noqa: E501
        """BillDiffList - a model defined in OpenAPI

        :param legislation_version_id: The legislation_version_id of this BillDiffList.  # noqa: E501
        :type legislation_version_id: int
        :param sections: The sections of this BillDiffList.  # noqa: E501
        :type sections: List[BillDiffMetadataItem]
        :param short_title: The short_title of this BillDiffList.  # noqa: E501
        :type short_title: str
        :param long_title: The long_title of this BillDiffList.  # noqa: E501
        :type long_title: str
        """
        self.openapi_types = {
            'legislation_version_id': int,
            'sections': List[BillDiffMetadataItem],
            'short_title': str,
            'long_title': str
        }

        self.attribute_map = {
            'legislation_version_id': 'legislation_version_id',
            'sections': 'sections',
            'short_title': 'short_title',
            'long_title': 'long_title'
        }

        self._legislation_version_id = legislation_version_id
        self._sections = sections
        self._short_title = short_title
        self._long_title = long_title

    @classmethod
    def from_dict(cls, dikt) -> 'BillDiffList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BillDiffList of this BillDiffList.  # noqa: E501
        :rtype: BillDiffList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def legislation_version_id(self):
        """Gets the legislation_version_id of this BillDiffList.


        :return: The legislation_version_id of this BillDiffList.
        :rtype: int
        """
        return self._legislation_version_id

    @legislation_version_id.setter
    def legislation_version_id(self, legislation_version_id):
        """Sets the legislation_version_id of this BillDiffList.


        :param legislation_version_id: The legislation_version_id of this BillDiffList.
        :type legislation_version_id: int
        """

        self._legislation_version_id = legislation_version_id

    @property
    def sections(self):
        """Gets the sections of this BillDiffList.


        :return: The sections of this BillDiffList.
        :rtype: List[BillDiffMetadataItem]
        """
        return self._sections

    @sections.setter
    def sections(self, sections):
        """Sets the sections of this BillDiffList.


        :param sections: The sections of this BillDiffList.
        :type sections: List[BillDiffMetadataItem]
        """

        self._sections = sections

    @property
    def short_title(self):
        """Gets the short_title of this BillDiffList.


        :return: The short_title of this BillDiffList.
        :rtype: str
        """
        return self._short_title

    @short_title.setter
    def short_title(self, short_title):
        """Sets the short_title of this BillDiffList.


        :param short_title: The short_title of this BillDiffList.
        :type short_title: str
        """

        self._short_title = short_title

    @property
    def long_title(self):
        """Gets the long_title of this BillDiffList.


        :return: The long_title of this BillDiffList.
        :rtype: str
        """
        return self._long_title

    @long_title.setter
    def long_title(self, long_title):
        """Sets the long_title of this BillDiffList.


        :param long_title: The long_title of this BillDiffList.
        :type long_title: str
        """

        self._long_title = long_title
