# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from congress_api.models.base_model_ import Model
from congress_api import util



class BillContentDiff(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, number=None, content_type=None, content_str=None, heading=None, section_display=None, order_number=None, usc_guid=None, usc_ident=None, usc_content_id=None, usc_section_id=None, usc_content_diff_id=None):  # noqa: E501
        """BillContentDiff - a model defined in OpenAPI

        :param number: The number of this BillContentDiff.  # noqa: E501
        :type number: str
        :param content_type: The content_type of this BillContentDiff.  # noqa: E501
        :type content_type: str
        :param content_str: The content_str of this BillContentDiff.  # noqa: E501
        :type content_str: str
        :param heading: The heading of this BillContentDiff.  # noqa: E501
        :type heading: str
        :param section_display: The section_display of this BillContentDiff.  # noqa: E501
        :type section_display: str
        :param order_number: The order_number of this BillContentDiff.  # noqa: E501
        :type order_number: int
        :param usc_guid: The usc_guid of this BillContentDiff.  # noqa: E501
        :type usc_guid: str
        :param usc_ident: The usc_ident of this BillContentDiff.  # noqa: E501
        :type usc_ident: str
        :param usc_content_id: The usc_content_id of this BillContentDiff.  # noqa: E501
        :type usc_content_id: int
        :param usc_section_id: The usc_section_id of this BillContentDiff.  # noqa: E501
        :type usc_section_id: int
        """
        self.openapi_types = {
            'number': str,
            'content_type': str,
            'content_str': str,
            'heading': str,
            'section_display': str,
            'order_number': int,
            'usc_guid': str,
            'usc_ident': str,
            'usc_content_id': int,
            'usc_section_id': int,
            'usc_content_diff_id': int
        }

        self.attribute_map = {
            'number': 'number',
            'content_type': 'content_type',
            'content_str': 'content_str',
            'heading': 'heading',
            'section_display': 'section_display',
            'order_number': 'order_number',
            'usc_guid': 'usc_guid',
            'usc_ident': 'usc_ident',
            'usc_content_id': 'usc_content_id',
            'usc_section_id': 'usc_section_id',
            'usc_content_diff_id': 'usc_content_diff_id',
        }

        self._number = number
        self._content_type = content_type
        self._content_str = content_str
        self._heading = heading
        self._section_display = section_display
        self._order_number = order_number
        self._usc_guid = usc_guid
        self._usc_ident = usc_ident
        self._usc_content_id = usc_content_id
        self._usc_content_diff_id = usc_content_diff_id
        self._usc_section_id = usc_section_id

    @classmethod
    def from_dict(cls, dikt) -> 'BillContentDiff':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BillContentDiff of this BillContentDiff.  # noqa: E501
        :rtype: BillContentDiff
        """
        return util.deserialize_model(dikt, cls)

    @property
    def number(self):
        """Gets the number of this BillContentDiff.


        :return: The number of this BillContentDiff.
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this BillContentDiff.


        :param number: The number of this BillContentDiff.
        :type number: str
        """

        self._number = number

    @property
    def content_type(self):
        """Gets the content_type of this BillContentDiff.


        :return: The content_type of this BillContentDiff.
        :rtype: str
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """Sets the content_type of this BillContentDiff.


        :param content_type: The content_type of this BillContentDiff.
        :type content_type: str
        """

        self._content_type = content_type

    @property
    def content_str(self):
        """Gets the content_str of this BillContentDiff.


        :return: The content_str of this BillContentDiff.
        :rtype: str
        """
        return self._content_str

    @content_str.setter
    def content_str(self, content_str):
        """Sets the content_str of this BillContentDiff.


        :param content_str: The content_str of this BillContentDiff.
        :type content_str: str
        """

        self._content_str = content_str

    @property
    def heading(self):
        """Gets the heading of this BillContentDiff.


        :return: The heading of this BillContentDiff.
        :rtype: str
        """
        return self._heading

    @heading.setter
    def heading(self, heading):
        """Sets the heading of this BillContentDiff.


        :param heading: The heading of this BillContentDiff.
        :type heading: str
        """

        self._heading = heading

    @property
    def section_display(self):
        """Gets the section_display of this BillContentDiff.


        :return: The section_display of this BillContentDiff.
        :rtype: str
        """
        return self._section_display

    @section_display.setter
    def section_display(self, section_display):
        """Sets the section_display of this BillContentDiff.


        :param section_display: The section_display of this BillContentDiff.
        :type section_display: str
        """

        self._section_display = section_display

    @property
    def order_number(self):
        """Gets the order_number of this BillContentDiff.


        :return: The order_number of this BillContentDiff.
        :rtype: int
        """
        return self._order_number

    @order_number.setter
    def order_number(self, order_number):
        """Sets the order_number of this BillContentDiff.


        :param order_number: The order_number of this BillContentDiff.
        :type order_number: int
        """

        self._order_number = order_number

    @property
    def usc_guid(self):
        """Gets the usc_guid of this BillContentDiff.


        :return: The usc_guid of this BillContentDiff.
        :rtype: str
        """
        return self._usc_guid

    @usc_guid.setter
    def usc_guid(self, usc_guid):
        """Sets the usc_guid of this BillContentDiff.


        :param usc_guid: The usc_guid of this BillContentDiff.
        :type usc_guid: str
        """

        self._usc_guid = usc_guid

    @property
    def usc_ident(self):
        """Gets the usc_ident of this BillContentDiff.


        :return: The usc_ident of this BillContentDiff.
        :rtype: str
        """
        return self._usc_ident

    @usc_ident.setter
    def usc_ident(self, usc_ident):
        """Sets the usc_ident of this BillContentDiff.


        :param usc_ident: The usc_ident of this BillContentDiff.
        :type usc_ident: str
        """

        self._usc_ident = usc_ident

    @property
    def usc_content_id(self):
        """Gets the usc_content_id of this BillContentDiff.


        :return: The usc_content_id of this BillContentDiff.
        :rtype: int
        """
        return self._usc_content_id

    @usc_content_id.setter
    def usc_content_id(self, usc_content_id):
        """Sets the usc_content_id of this BillContentDiff.


        :param usc_content_id: The usc_content_id of this BillContentDiff.
        :type usc_content_id: int
        """

        self._usc_content_id = usc_content_id

    @property
    def usc_content_diff_id(self):
        """Gets the usc_content_id of this BillContentDiff.


        :return: The usc_content_id of this BillContentDiff.
        :rtype: int
        """
        return self._usc_content_diff_id

    @usc_content_diff_id.setter
    def usc_content_diff_id(self, usc_content_diff_id):
        """Sets the usc_content_id of this BillContentDiff.


        :param usc_content_id: The usc_content_id of this BillContentDiff.
        :type usc_content_id: int
        """

        self._usc_content_diff_id = usc_content_diff_id

    @property
    def usc_section_id(self):
        """Gets the usc_section_id of this BillContentDiff.


        :return: The usc_section_id of this BillContentDiff.
        :rtype: int
        """
        return self._usc_section_id

    @usc_section_id.setter
    def usc_section_id(self, usc_section_id):
        """Sets the usc_section_id of this BillContentDiff.


        :param usc_section_id: The usc_section_id of this BillContentDiff.
        :type usc_section_id: int
        """

        self._usc_section_id = usc_section_id
