# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from congress_api import util
from congress_api.models.base_model_ import Model


class BillSlimMetadata(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(
        self,
        legislation_id=None,
        title=None,
        number=None,
        congress_id=None,
        legislation_type=None,
        legislation_versions=None,
    ):  # noqa: E501
        """BillSlimMetadata - a model defined in OpenAPI

        :param legislation_id: The legislation_id of this BillSlimMetadata.  # noqa: E501
        :type legislation_id: int
        :param title: The title of this BillSlimMetadata.  # noqa: E501
        :type title: str
        :param number: The number of this BillSlimMetadata.  # noqa: E501
        :type number: int
        :param congress_id: The congress_id of this BillSlimMetadata.  # noqa: E501
        :type congress_id: int
        :param legislation_type: The legislation_type of this BillSlimMetadata.  # noqa: E501
        :type legislation_type: str
        :param legislation_versions: The legislation_versions of this BillSlimMetadata.  # noqa: E501
        :type legislation_versions: List[str]
        """
        self.openapi_types = {
            "legislation_id": int,
            "title": str,
            "number": int,
            "congress_id": int,
            "legislation_type": str,
            "legislation_versions": List[str],
        }

        self.attribute_map = {
            "legislation_id": "legislation_id",
            "title": "title",
            "number": "number",
            "congress_id": "congress_id",
            "legislation_type": "legislation_type",
            "legislation_versions": "legislation_versions",
        }

        self._legislation_id = legislation_id
        self._title = title
        self._number = number
        self._congress_id = congress_id
        self._legislation_type = legislation_type
        self._legislation_versions = legislation_versions

    @classmethod
    def from_dict(cls, dikt) -> "BillSlimMetadata":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BillSlimMetadata of this BillSlimMetadata.  # noqa: E501
        :rtype: BillSlimMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def legislation_id(self):
        """Gets the legislation_id of this BillSlimMetadata.


        :return: The legislation_id of this BillSlimMetadata.
        :rtype: int
        """
        return self._legislation_id

    @legislation_id.setter
    def legislation_id(self, legislation_id):
        """Sets the legislation_id of this BillSlimMetadata.


        :param legislation_id: The legislation_id of this BillSlimMetadata.
        :type legislation_id: int
        """

        self._legislation_id = legislation_id

    @property
    def title(self):
        """Gets the title of this BillSlimMetadata.


        :return: The title of this BillSlimMetadata.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this BillSlimMetadata.


        :param title: The title of this BillSlimMetadata.
        :type title: str
        """

        self._title = title

    @property
    def number(self):
        """Gets the number of this BillSlimMetadata.


        :return: The number of this BillSlimMetadata.
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this BillSlimMetadata.


        :param number: The number of this BillSlimMetadata.
        :type number: int
        """

        self._number = number

    @property
    def congress_id(self):
        """Gets the congress_id of this BillSlimMetadata.


        :return: The congress_id of this BillSlimMetadata.
        :rtype: int
        """
        return self._congress_id

    @congress_id.setter
    def congress_id(self, congress_id):
        """Sets the congress_id of this BillSlimMetadata.


        :param congress_id: The congress_id of this BillSlimMetadata.
        :type congress_id: int
        """

        self._congress_id = congress_id

    @property
    def legislation_type(self):
        """Gets the legislation_type of this BillSlimMetadata.


        :return: The legislation_type of this BillSlimMetadata.
        :rtype: str
        """
        return self._legislation_type

    @legislation_type.setter
    def legislation_type(self, legislation_type):
        """Sets the legislation_type of this BillSlimMetadata.


        :param legislation_type: The legislation_type of this BillSlimMetadata.
        :type legislation_type: str
        """

        self._legislation_type = legislation_type

    @property
    def legislation_versions(self):
        """Gets the legislation_versions of this BillSlimMetadata.


        :return: The legislation_versions of this BillSlimMetadata.
        :rtype: List[str]
        """
        return self._legislation_versions

    @legislation_versions.setter
    def legislation_versions(self, legislation_versions):
        """Sets the legislation_versions of this BillSlimMetadata.


        :param legislation_versions: The legislation_versions of this BillSlimMetadata.
        :type legislation_versions: List[str]
        """

        self._legislation_versions = legislation_versions
