# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from congress_api import util
from congress_api.models.base_model_ import Model
from congress_api.models.bill_slim_metadata import BillSlimMetadata  # noqa: E501


class ChamberBillList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(
        self,
        chamber=None,
        conress_id=None,
        legislation=None,
        bill_start=None,
        bill_end=None,
    ):  # noqa: E501
        """ChamberBillList - a model defined in OpenAPI

        :param chamber: The chamber of this ChamberBillList.  # noqa: E501
        :type chamber: str
        :param conress_id: The conress_id of this ChamberBillList.  # noqa: E501
        :type conress_id: int
        :param legislation: The legislation of this ChamberBillList.  # noqa: E501
        :type legislation: List[BillSlimMetadata]
        :param bill_start: The bill_start of this ChamberBillList.  # noqa: E501
        :type bill_start: int
        :param bill_end: The bill_end of this ChamberBillList.  # noqa: E501
        :type bill_end: int
        """
        self.openapi_types = {
            "chamber": str,
            "conress_id": int,
            "legislation": List[BillSlimMetadata],
            "bill_start": int,
            "bill_end": int,
        }

        self.attribute_map = {
            "chamber": "chamber",
            "conress_id": "conress_id",
            "legislation": "legislation",
            "bill_start": "bill_start",
            "bill_end": "bill_end",
        }

        self._chamber = chamber
        self._conress_id = conress_id
        self._legislation = legislation
        self._bill_start = bill_start
        self._bill_end = bill_end

    @classmethod
    def from_dict(cls, dikt) -> "ChamberBillList":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChamberBillList of this ChamberBillList.  # noqa: E501
        :rtype: ChamberBillList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def chamber(self):
        """Gets the chamber of this ChamberBillList.


        :return: The chamber of this ChamberBillList.
        :rtype: str
        """
        return self._chamber

    @chamber.setter
    def chamber(self, chamber):
        """Sets the chamber of this ChamberBillList.


        :param chamber: The chamber of this ChamberBillList.
        :type chamber: str
        """

        self._chamber = chamber

    @property
    def conress_id(self):
        """Gets the conress_id of this ChamberBillList.


        :return: The conress_id of this ChamberBillList.
        :rtype: int
        """
        return self._conress_id

    @conress_id.setter
    def conress_id(self, conress_id):
        """Sets the conress_id of this ChamberBillList.


        :param conress_id: The conress_id of this ChamberBillList.
        :type conress_id: int
        """

        self._conress_id = conress_id

    @property
    def legislation(self):
        """Gets the legislation of this ChamberBillList.


        :return: The legislation of this ChamberBillList.
        :rtype: List[BillSlimMetadata]
        """
        return self._legislation

    @legislation.setter
    def legislation(self, legislation):
        """Sets the legislation of this ChamberBillList.


        :param legislation: The legislation of this ChamberBillList.
        :type legislation: List[BillSlimMetadata]
        """

        self._legislation = legislation

    @property
    def bill_start(self):
        """Gets the bill_start of this ChamberBillList.


        :return: The bill_start of this ChamberBillList.
        :rtype: int
        """
        return self._bill_start

    @bill_start.setter
    def bill_start(self, bill_start):
        """Sets the bill_start of this ChamberBillList.


        :param bill_start: The bill_start of this ChamberBillList.
        :type bill_start: int
        """

        self._bill_start = bill_start

    @property
    def bill_end(self):
        """Gets the bill_end of this ChamberBillList.


        :return: The bill_end of this ChamberBillList.
        :rtype: int
        """
        return self._bill_end

    @bill_end.setter
    def bill_end(self, bill_end):
        """Sets the bill_end of this ChamberBillList.


        :param bill_end: The bill_end of this ChamberBillList.
        :type bill_end: int
        """

        self._bill_end = bill_end
