# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

import connexion

from congress_api import util
from congress_api.models.base_model_ import Model


class ErrorResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
    Do not edit the class manually.
    """

    def __init__(self, request_url=None, message=None):  # noqa: E501
        """ErrorResponse - a model defined in OpenAPI
        :param request_url: The request_url of this ErrorResponse.  # noqa: E501
        :type request_url: str
        :param message: The message of this ErrorResponse.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {"request_url": str, "message": str}

        self.attribute_map = {"request_url": "request_url", "message": "message"}

        self._request_url = request_url or connexion.request.url
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> "ErrorResponse":
        """Returns the dict as a model
        :param dikt: A dict.
        :type: dict
        :return: The ErrorResponse of this ErrorResponse.  # noqa: E501
        :rtype: ErrorResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def request_url(self):
        """Gets the request_url of this ErrorResponse.
        :return: The request_url of this ErrorResponse.
        :rtype: str
        """
        return self._request_url

    @request_url.setter
    def request_url(self, request_url):
        """Sets the request_url of this ErrorResponse.
        :param request_url: The request_url of this ErrorResponse.
        :type request_url: str
        """

        self._request_url = request_url

    @property
    def message(self):
        """Gets the message of this ErrorResponse.
        :return: The message of this ErrorResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ErrorResponse.
        :param message: The message of this ErrorResponse.
        :type message: str
        """

        self._message = message
