# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from congress_api import util
from congress_api.models.base_model_ import Model


class NotFound(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, request_url=None, message=None):  # noqa: E501
        """NotFound - a model defined in OpenAPI

        :param request_url: The request_url of this NotFound.  # noqa: E501
        :type request_url: str
        :param message: The message of this NotFound.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {"request_url": str, "message": str}

        self.attribute_map = {"request_url": "request_url", "message": "message"}

        self._request_url = request_url
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> "NotFound":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NotFound of this NotFound.  # noqa: E501
        :rtype: NotFound
        """
        return util.deserialize_model(dikt, cls)

    @property
    def request_url(self):
        """Gets the request_url of this NotFound.


        :return: The request_url of this NotFound.
        :rtype: str
        """
        return self._request_url

    @request_url.setter
    def request_url(self, request_url):
        """Sets the request_url of this NotFound.


        :param request_url: The request_url of this NotFound.
        :type request_url: str
        """

        self._request_url = request_url

    @property
    def message(self):
        """Gets the message of this NotFound.


        :return: The message of this NotFound.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this NotFound.


        :param message: The message of this NotFound.
        :type message: str
        """

        self._message = message
