# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from congress_api import util
from congress_api.models.base_model_ import Model


class ReleasePointMetadata(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(
        self,
        usc_release_id=None,
        short_title=None,
        effective_date=None,
        long_title=None,
    ):  # noqa: E501
        """ReleasePointMetadata - a model defined in OpenAPI

        :param usc_release_id: The usc_release_id of this ReleasePointMetadata.  # noqa: E501
        :type usc_release_id: int
        :param short_title: The short_title of this ReleasePointMetadata.  # noqa: E501
        :type short_title: str
        :param effective_date: The effective_date of this ReleasePointMetadata.  # noqa: E501
        :type effective_date: str
        :param long_title: The long_title of this ReleasePointMetadata.  # noqa: E501
        :type long_title: str
        """
        self.openapi_types = {
            "usc_release_id": int,
            "short_title": str,
            "effective_date": str,
            "long_title": str,
        }

        self.attribute_map = {
            "usc_release_id": "usc_release_id",
            "short_title": "short_title",
            "effective_date": "effective_date",
            "long_title": "long_title",
        }

        self._usc_release_id = usc_release_id
        self._short_title = short_title
        self._effective_date = effective_date
        self._long_title = long_title

    @classmethod
    def from_dict(cls, dikt) -> "ReleasePointMetadata":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReleasePointMetadata of this ReleasePointMetadata.  # noqa: E501
        :rtype: ReleasePointMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def usc_release_id(self):
        """Gets the usc_release_id of this ReleasePointMetadata.


        :return: The usc_release_id of this ReleasePointMetadata.
        :rtype: int
        """
        return self._usc_release_id

    @usc_release_id.setter
    def usc_release_id(self, usc_release_id):
        """Sets the usc_release_id of this ReleasePointMetadata.


        :param usc_release_id: The usc_release_id of this ReleasePointMetadata.
        :type usc_release_id: int
        """

        self._usc_release_id = usc_release_id

    @property
    def short_title(self):
        """Gets the short_title of this ReleasePointMetadata.


        :return: The short_title of this ReleasePointMetadata.
        :rtype: str
        """
        return self._short_title

    @short_title.setter
    def short_title(self, short_title):
        """Sets the short_title of this ReleasePointMetadata.


        :param short_title: The short_title of this ReleasePointMetadata.
        :type short_title: str
        """

        self._short_title = short_title

    @property
    def effective_date(self):
        """Gets the effective_date of this ReleasePointMetadata.


        :return: The effective_date of this ReleasePointMetadata.
        :rtype: str
        """
        return self._effective_date

    @effective_date.setter
    def effective_date(self, effective_date):
        """Sets the effective_date of this ReleasePointMetadata.


        :param effective_date: The effective_date of this ReleasePointMetadata.
        :type effective_date: str
        """

        self._effective_date = effective_date

    @property
    def long_title(self):
        """Gets the long_title of this ReleasePointMetadata.


        :return: The long_title of this ReleasePointMetadata.
        :rtype: str
        """
        return self._long_title

    @long_title.setter
    def long_title(self, long_title):
        """Sets the long_title of this ReleasePointMetadata.


        :param long_title: The long_title of this ReleasePointMetadata.
        :type long_title: str
        """

        self._long_title = long_title
