# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from congress_api import util
from congress_api.models.base_model_ import Model


class USCTitleMetadata(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(
        self,
        usc_chapter_id=None,
        short_title=None,
        long_title=None,
        usc_release_id=None,
    ):  # noqa: E501
        """USCTitleMetadata - a model defined in OpenAPI

        :param usc_chapter_id: The usc_chapter_id of this USCTitleMetadata.  # noqa: E501
        :type usc_chapter_id: int
        :param short_title: The short_title of this USCTitleMetadata.  # noqa: E501
        :type short_title: str
        :param long_title: The long_title of this USCTitleMetadata.  # noqa: E501
        :type long_title: str
        :param usc_release_id: The usc_release_id of this USCTitleMetadata.  # noqa: E501
        :type usc_release_id: int
        """
        self.openapi_types = {
            "usc_chapter_id": int,
            "short_title": str,
            "long_title": str,
            "usc_release_id": int,
        }

        self.attribute_map = {
            "usc_chapter_id": "usc_chapter_id",
            "short_title": "short_title",
            "long_title": "long_title",
            "usc_release_id": "usc_release_id",
        }

        self._usc_chapter_id = usc_chapter_id
        self._short_title = short_title
        self._long_title = long_title
        self._usc_release_id = usc_release_id

    @classmethod
    def from_dict(cls, dikt) -> "USCTitleMetadata":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The USCTitleMetadata of this USCTitleMetadata.  # noqa: E501
        :rtype: USCTitleMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def usc_chapter_id(self):
        """Gets the usc_chapter_id of this USCTitleMetadata.


        :return: The usc_chapter_id of this USCTitleMetadata.
        :rtype: int
        """
        return self._usc_chapter_id

    @usc_chapter_id.setter
    def usc_chapter_id(self, usc_chapter_id):
        """Sets the usc_chapter_id of this USCTitleMetadata.


        :param usc_chapter_id: The usc_chapter_id of this USCTitleMetadata.
        :type usc_chapter_id: int
        """

        self._usc_chapter_id = usc_chapter_id

    @property
    def short_title(self):
        """Gets the short_title of this USCTitleMetadata.


        :return: The short_title of this USCTitleMetadata.
        :rtype: str
        """
        return self._short_title

    @short_title.setter
    def short_title(self, short_title):
        """Sets the short_title of this USCTitleMetadata.


        :param short_title: The short_title of this USCTitleMetadata.
        :type short_title: str
        """

        self._short_title = short_title

    @property
    def long_title(self):
        """Gets the long_title of this USCTitleMetadata.


        :return: The long_title of this USCTitleMetadata.
        :rtype: str
        """
        return self._long_title

    @long_title.setter
    def long_title(self, long_title):
        """Sets the long_title of this USCTitleMetadata.


        :param long_title: The long_title of this USCTitleMetadata.
        :type long_title: str
        """

        self._long_title = long_title

    @property
    def usc_release_id(self):
        """Gets the usc_release_id of this USCTitleMetadata.


        :return: The usc_release_id of this USCTitleMetadata.
        :rtype: int
        """
        return self._usc_release_id

    @usc_release_id.setter
    def usc_release_id(self, usc_release_id):
        """Sets the usc_release_id of this USCTitleMetadata.


        :param usc_release_id: The usc_release_id of this USCTitleMetadata.
        :type usc_release_id: int
        """

        self._usc_release_id = usc_release_id
