# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from congress_api import util
from congress_api.models.base_model_ import Model


class USCTitleList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, titles=None):  # noqa: E501
        """USCTitleList - a model defined in OpenAPI

        :param titles: The titles of this USCTitleList.  # noqa: E501
        :type titles: List[object]
        """
        self.openapi_types = {"titles": List[object]}

        self.attribute_map = {"titles": "titles"}

        self._titles = titles

    @classmethod
    def from_dict(cls, dikt) -> "USCTitleList":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The USCTitleList of this USCTitleList.  # noqa: E501
        :rtype: USCTitleList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def titles(self):
        """Gets the titles of this USCTitleList.


        :return: The titles of this USCTitleList.
        :rtype: List[object]
        """
        return self._titles

    @titles.setter
    def titles(self, titles):
        """Sets the titles of this USCTitleList.


        :param titles: The titles of this USCTitleList.
        :type titles: List[object]
        """

        self._titles = titles
