# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from congress_api.models.base_model_ import Model
from congress_api import util


class USCSectionMetadata(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(
        self,
        usc_section_id=None,
        usc_ident=None,
        usc_guid=None,
        number=None,
        section_display=None,
        heading=None,
        usc_chapter_id=None,
        parent_id=None,
        content_type=None,
    ):  # noqa: E501
        """USCSectionMetadata - a model defined in OpenAPI

        :param usc_section_id: The usc_section_id of this USCSectionMetadata.  # noqa: E501
        :type usc_section_id: int
        :param usc_ident: The usc_ident of this USCSectionMetadata.  # noqa: E501
        :type usc_ident: str
        :param usc_guid: The usc_guid of this USCSectionMetadata.  # noqa: E501
        :type usc_guid: str
        :param number: The number of this USCSectionMetadata.  # noqa: E501
        :type number: str
        :param section_display: The section_display of this USCSectionMetadata.  # noqa: E501
        :type section_display: str
        :param heading: The heading of this USCSectionMetadata.  # noqa: E501
        :type heading: str
        :param usc_chapter_id: The usc_chapter_id of this USCSectionMetadata.  # noqa: E501
        :type usc_chapter_id: int
        :param parent_id: The parent_id of this USCSectionMetadata.  # noqa: E501
        :type parent_id: int
        :param content_type: The content_type of this USCSectionMetadata.  # noqa: E501
        :type content_type: str
        """
        self.openapi_types = {
            "usc_section_id": int,
            "usc_ident": str,
            "usc_guid": str,
            "number": str,
            "section_display": str,
            "heading": str,
            "usc_chapter_id": int,
            "parent_id": int,
            "content_type": str,
        }

        self.attribute_map = {
            "usc_section_id": "usc_section_id",
            "usc_ident": "usc_ident",
            "usc_guid": "usc_guid",
            "number": "number",
            "section_display": "section_display",
            "heading": "heading",
            "usc_chapter_id": "usc_chapter_id",
            "parent_id": "parent_id",
            "content_type": "content_type",
        }

        self._usc_section_id = usc_section_id
        self._usc_ident = usc_ident
        self._usc_guid = usc_guid
        self._number = number
        self._section_display = section_display
        self._heading = heading
        self._usc_chapter_id = usc_chapter_id
        self._parent_id = parent_id
        self._content_type = content_type

    @classmethod
    def from_dict(cls, dikt) -> "USCSectionMetadata":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The USCSectionMetadata of this USCSectionMetadata.  # noqa: E501
        :rtype: USCSectionMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def usc_section_id(self):
        """Gets the usc_section_id of this USCSectionMetadata.


        :return: The usc_section_id of this USCSectionMetadata.
        :rtype: int
        """
        return self._usc_section_id

    @usc_section_id.setter
    def usc_section_id(self, usc_section_id):
        """Sets the usc_section_id of this USCSectionMetadata.


        :param usc_section_id: The usc_section_id of this USCSectionMetadata.
        :type usc_section_id: int
        """

        self._usc_section_id = usc_section_id

    @property
    def usc_ident(self):
        """Gets the usc_ident of this USCSectionMetadata.


        :return: The usc_ident of this USCSectionMetadata.
        :rtype: str
        """
        return self._usc_ident

    @usc_ident.setter
    def usc_ident(self, usc_ident):
        """Sets the usc_ident of this USCSectionMetadata.


        :param usc_ident: The usc_ident of this USCSectionMetadata.
        :type usc_ident: str
        """

        self._usc_ident = usc_ident

    @property
    def usc_guid(self):
        """Gets the usc_guid of this USCSectionMetadata.


        :return: The usc_guid of this USCSectionMetadata.
        :rtype: str
        """
        return self._usc_guid

    @usc_guid.setter
    def usc_guid(self, usc_guid):
        """Sets the usc_guid of this USCSectionMetadata.


        :param usc_guid: The usc_guid of this USCSectionMetadata.
        :type usc_guid: str
        """

        self._usc_guid = usc_guid

    @property
    def number(self):
        """Gets the number of this USCSectionMetadata.


        :return: The number of this USCSectionMetadata.
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this USCSectionMetadata.


        :param number: The number of this USCSectionMetadata.
        :type number: str
        """

        self._number = number

    @property
    def section_display(self):
        """Gets the section_display of this USCSectionMetadata.


        :return: The section_display of this USCSectionMetadata.
        :rtype: str
        """
        return self._section_display

    @section_display.setter
    def section_display(self, section_display):
        """Sets the section_display of this USCSectionMetadata.


        :param section_display: The section_display of this USCSectionMetadata.
        :type section_display: str
        """

        self._section_display = section_display

    @property
    def heading(self):
        """Gets the heading of this USCSectionMetadata.


        :return: The heading of this USCSectionMetadata.
        :rtype: str
        """
        return self._heading

    @heading.setter
    def heading(self, heading):
        """Sets the heading of this USCSectionMetadata.


        :param heading: The heading of this USCSectionMetadata.
        :type heading: str
        """

        self._heading = heading

    @property
    def usc_chapter_id(self):
        """Gets the usc_chapter_id of this USCSectionMetadata.


        :return: The usc_chapter_id of this USCSectionMetadata.
        :rtype: int
        """
        return self._usc_chapter_id

    @usc_chapter_id.setter
    def usc_chapter_id(self, usc_chapter_id):
        """Sets the usc_chapter_id of this USCSectionMetadata.


        :param usc_chapter_id: The usc_chapter_id of this USCSectionMetadata.
        :type usc_chapter_id: int
        """

        self._usc_chapter_id = usc_chapter_id

    @property
    def parent_id(self):
        """Gets the parent_id of this USCSectionMetadata.


        :return: The parent_id of this USCSectionMetadata.
        :rtype: int
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id):
        """Sets the parent_id of this USCSectionMetadata.


        :param parent_id: The parent_id of this USCSectionMetadata.
        :type parent_id: int
        """

        self._parent_id = parent_id

    @property
    def content_type(self):
        """Gets the content_type of this USCSectionMetadata.


        :return: The content_type of this USCSectionMetadata.
        :rtype: str
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """Sets the content_type of this USCSectionMetadata.


        :param content_type: The content_type of this USCSectionMetadata.
        :type content_type: str
        """

        self._content_type = content_type
