# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from congress_api import util
from congress_api.models.base_model_ import Model


class USCSectionContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(
        self,
        usc_content_id=None,
        usc_ident=None,
        usc_guid=None,
        parent_id=None,
        order_number=None,
        section_display=None,
        heading=None,
        content_str=None,
        content_type=None,
        number=None,
        usc_section_id=None,
    ):  # noqa: E501
        """USCSectionContent - a model defined in OpenAPI

        :param usc_content_id: The usc_content_id of this USCSectionContent.  # noqa: E501
        :type usc_content_id: int
        :param usc_ident: The usc_ident of this USCSectionContent.  # noqa: E501
        :type usc_ident: str
        :param usc_guid: The usc_guid of this USCSectionContent.  # noqa: E501
        :type usc_guid: str
        :param parent_id: The parent_id of this USCSectionContent.  # noqa: E501
        :type parent_id: int
        :param order_number: The order_number of this USCSectionContent.  # noqa: E501
        :type order_number: int
        :param section_display: The section_display of this USCSectionContent.  # noqa: E501
        :type section_display: str
        :param heading: The heading of this USCSectionContent.  # noqa: E501
        :type heading: str
        :param content_str: The content_str of this USCSectionContent.  # noqa: E501
        :type content_str: str
        :param content_type: The content_type of this USCSectionContent.  # noqa: E501
        :type content_type: str
        :param number: The number of this USCSectionContent.  # noqa: E501
        :type number: str
        :param usc_section_id: The usc_section_id of this USCSectionContent.  # noqa: E501
        :type usc_section_id: int
        """
        self.openapi_types = {
            "usc_content_id": int,
            "usc_ident": str,
            "usc_guid": str,
            "parent_id": int,
            "order_number": int,
            "section_display": str,
            "heading": str,
            "content_str": str,
            "content_type": str,
            "number": str,
            "usc_section_id": int,
        }

        self.attribute_map = {
            "usc_content_id": "usc_content_id",
            "usc_ident": "usc_ident",
            "usc_guid": "usc_guid",
            "parent_id": "parent_id",
            "order_number": "order_number",
            "section_display": "section_display",
            "heading": "heading",
            "content_str": "content_str",
            "content_type": "content_type",
            "number": "number",
            "usc_section_id": "usc_section_id",
        }

        self._usc_content_id = usc_content_id
        self._usc_ident = usc_ident
        self._usc_guid = usc_guid
        self._parent_id = parent_id
        self._order_number = order_number
        self._section_display = section_display
        self._heading = heading
        self._content_str = content_str
        self._content_type = content_type
        self._number = number
        self._usc_section_id = usc_section_id

    @classmethod
    def from_dict(cls, dikt) -> "USCSectionContent":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The USCSectionContent of this USCSectionContent.  # noqa: E501
        :rtype: USCSectionContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def usc_content_id(self):
        """Gets the usc_content_id of this USCSectionContent.


        :return: The usc_content_id of this USCSectionContent.
        :rtype: int
        """
        return self._usc_content_id

    @usc_content_id.setter
    def usc_content_id(self, usc_content_id):
        """Sets the usc_content_id of this USCSectionContent.


        :param usc_content_id: The usc_content_id of this USCSectionContent.
        :type usc_content_id: int
        """

        self._usc_content_id = usc_content_id

    @property
    def usc_ident(self):
        """Gets the usc_ident of this USCSectionContent.


        :return: The usc_ident of this USCSectionContent.
        :rtype: str
        """
        return self._usc_ident

    @usc_ident.setter
    def usc_ident(self, usc_ident):
        """Sets the usc_ident of this USCSectionContent.


        :param usc_ident: The usc_ident of this USCSectionContent.
        :type usc_ident: str
        """

        self._usc_ident = usc_ident

    @property
    def usc_guid(self):
        """Gets the usc_guid of this USCSectionContent.


        :return: The usc_guid of this USCSectionContent.
        :rtype: str
        """
        return self._usc_guid

    @usc_guid.setter
    def usc_guid(self, usc_guid):
        """Sets the usc_guid of this USCSectionContent.


        :param usc_guid: The usc_guid of this USCSectionContent.
        :type usc_guid: str
        """

        self._usc_guid = usc_guid

    @property
    def parent_id(self):
        """Gets the parent_id of this USCSectionContent.


        :return: The parent_id of this USCSectionContent.
        :rtype: int
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id):
        """Sets the parent_id of this USCSectionContent.


        :param parent_id: The parent_id of this USCSectionContent.
        :type parent_id: int
        """

        self._parent_id = parent_id

    @property
    def order_number(self):
        """Gets the order_number of this USCSectionContent.


        :return: The order_number of this USCSectionContent.
        :rtype: int
        """
        return self._order_number

    @order_number.setter
    def order_number(self, order_number):
        """Sets the order_number of this USCSectionContent.


        :param order_number: The order_number of this USCSectionContent.
        :type order_number: int
        """

        self._order_number = order_number

    @property
    def section_display(self):
        """Gets the section_display of this USCSectionContent.


        :return: The section_display of this USCSectionContent.
        :rtype: str
        """
        return self._section_display

    @section_display.setter
    def section_display(self, section_display):
        """Sets the section_display of this USCSectionContent.


        :param section_display: The section_display of this USCSectionContent.
        :type section_display: str
        """

        self._section_display = section_display

    @property
    def heading(self):
        """Gets the heading of this USCSectionContent.


        :return: The heading of this USCSectionContent.
        :rtype: str
        """
        return self._heading

    @heading.setter
    def heading(self, heading):
        """Sets the heading of this USCSectionContent.


        :param heading: The heading of this USCSectionContent.
        :type heading: str
        """

        self._heading = heading

    @property
    def content_str(self):
        """Gets the content_str of this USCSectionContent.


        :return: The content_str of this USCSectionContent.
        :rtype: str
        """
        return self._content_str

    @content_str.setter
    def content_str(self, content_str):
        """Sets the content_str of this USCSectionContent.


        :param content_str: The content_str of this USCSectionContent.
        :type content_str: str
        """

        self._content_str = content_str

    @property
    def content_type(self):
        """Gets the content_type of this USCSectionContent.


        :return: The content_type of this USCSectionContent.
        :rtype: str
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """Sets the content_type of this USCSectionContent.


        :param content_type: The content_type of this USCSectionContent.
        :type content_type: str
        """

        self._content_type = content_type

    @property
    def number(self):
        """Gets the number of this USCSectionContent.


        :return: The number of this USCSectionContent.
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this USCSectionContent.


        :param number: The number of this USCSectionContent.
        :type number: str
        """

        self._number = number

    @property
    def usc_section_id(self):
        """Gets the usc_section_id of this USCSectionContent.


        :return: The usc_section_id of this USCSectionContent.
        :rtype: int
        """
        return self._usc_section_id

    @usc_section_id.setter
    def usc_section_id(self, usc_section_id):
        """Sets the usc_section_id of this USCSectionContent.


        :param usc_section_id: The usc_section_id of this USCSectionContent.
        :type usc_section_id: int
        """

        self._usc_section_id = usc_section_id
