# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from congress_api import util
from congress_api.models.base_model_ import Model
from congress_api.models.usc_section_content import USCSectionContent  # noqa: E501


class USCSectionContentList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, usc_section_id=None, content=None):  # noqa: E501
        """USCSectionContentList - a model defined in OpenAPI

        :param usc_section_id: The usc_section_id of this USCSectionContentList.  # noqa: E501
        :type usc_section_id: int
        :param content: The content of this USCSectionContentList.  # noqa: E501
        :type content: List[USCSectionContent]
        """
        self.openapi_types = {"usc_section_id": int, "content": List[USCSectionContent]}

        self.attribute_map = {"usc_section_id": "usc_section_id", "content": "content"}

        self._usc_section_id = usc_section_id
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> "USCSectionContentList":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The USCSectionContentList of this USCSectionContentList.  # noqa: E501
        :rtype: USCSectionContentList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def usc_section_id(self):
        """Gets the usc_section_id of this USCSectionContentList.


        :return: The usc_section_id of this USCSectionContentList.
        :rtype: int
        """
        return self._usc_section_id

    @usc_section_id.setter
    def usc_section_id(self, usc_section_id):
        """Sets the usc_section_id of this USCSectionContentList.


        :param usc_section_id: The usc_section_id of this USCSectionContentList.
        :type usc_section_id: int
        """

        self._usc_section_id = usc_section_id

    @property
    def content(self):
        """Gets the content of this USCSectionContentList.


        :return: The content of this USCSectionContentList.
        :rtype: List[USCSectionContent]
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this USCSectionContentList.


        :param content: The content of this USCSectionContentList.
        :type content: List[USCSectionContent]
        """

        self._content = content
