# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from congress_api import util
from congress_api.models.base_model_ import Model


class USCSectionList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, usc_chapter_id=None, sections=None):  # noqa: E501
        """USCSectionList - a model defined in OpenAPI

        :param usc_chapter_id: The usc_chapter_id of this USCSectionList.  # noqa: E501
        :type usc_chapter_id: int
        :param offset: The offset of this USCSectionList.  # noqa: E501
        :type offset: int
        :param total: The total of this USCSectionList.  # noqa: E501
        :type total: int
        :param sections: The sections of this USCSectionList.  # noqa: E501
        :type sections: List[object]
        """
        self.openapi_types = {"usc_chapter_id": int, "sections": List[object]}

        self.attribute_map = {
            "usc_chapter_id": "usc_chapter_id",
            "sections": "sections",
        }

        self._usc_chapter_id = usc_chapter_id
        self._sections = sections

    @classmethod
    def from_dict(cls, dikt) -> "USCSectionList":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The USCSectionList of this USCSectionList.  # noqa: E501
        :rtype: USCSectionList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def usc_chapter_id(self):
        """Gets the usc_chapter_id of this USCSectionList.


        :return: The usc_chapter_id of this USCSectionList.
        :rtype: int
        """
        return self._usc_chapter_id

    @usc_chapter_id.setter
    def usc_chapter_id(self, usc_chapter_id):
        """Sets the usc_chapter_id of this USCSectionList.


        :param usc_chapter_id: The usc_chapter_id of this USCSectionList.
        :type usc_chapter_id: int
        """

        self._usc_chapter_id = usc_chapter_id

    @property
    def sections(self):
        """Gets the sections of this USCSectionList.


        :return: The sections of this USCSectionList.
        :rtype: List[object]
        """
        return self._sections

    @sections.setter
    def sections(self, sections):
        """Sets the sections of this USCSectionList.


        :param sections: The sections of this USCSectionList.
        :type sections: List[object]
        """

        self._sections = sections
