"""Initial

Revision ID: 25859598b635
Revises: 
Create Date: 2024-01-10 21:34:57.891802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import JSONB, ARRAY
import billparser

# revision identifiers, used by Alembic.
revision: str = '25859598b635'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('congress',
    sa.Column('congress_id', sa.Integer(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('congress_id')
    )
    op.create_table('legislation_committee',
    sa.Column('legislation_committee_id', sa.Integer(), nullable=False),
    sa.Column('system_code', sa.String(), nullable=True),
    sa.Column('chamber', sa.Enum('House', 'Senate', name='legislationchamber'), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('committee_type', sa.String(), nullable=True),
    sa.Column('subcommittee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subcommittee'], ['legislation_committee.legislation_committee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('legislation_committee_id')
    )
    op.create_index(op.f('ix_legislation_committee_subcommittee'), 'legislation_committee', ['subcommittee'], unique=False)
    op.create_table('version',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('base_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['base_id'], ['version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_version_base_id'), 'version', ['base_id'], unique=False)
    op.create_table('legislation',
    sa.Column('legislation_id', sa.Integer(), nullable=False),
    sa.Column('chamber', sa.Enum('House', 'Senate', name='legislationchamber'), nullable=True),
    sa.Column('legislation_type', sa.Enum('Bill', 'CRes', 'Res', 'JRes', name='legislationtype'), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('congress_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('policy_areas', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('legislative_subjects', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['congress_id'], ['congress.congress_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('legislation_id'),
    sa.UniqueConstraint('chamber', 'number', 'legislation_type', name='unq_bill')
    )
    op.create_index(op.f('ix_legislation_chamber'), 'legislation', ['chamber'], unique=False)
    op.create_index(op.f('ix_legislation_legislative_subjects'), 'legislation', ['legislative_subjects'], unique=False)
    op.create_index(op.f('ix_legislation_policy_areas'), 'legislation', ['policy_areas'], unique=False)
    op.create_table('usc_release',
    sa.Column('usc_release_id', sa.Integer(), nullable=False),
    sa.Column('short_title', sa.String(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('long_title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usc_release_id')
    )
    op.create_table('legislation_committee_association',
    sa.Column('committee_association_id', sa.Integer(), nullable=False),
    sa.Column('legislation_committee_id', sa.Integer(), nullable=True),
    sa.Column('referred_date', sa.DateTime(), nullable=True),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('legislation_id', sa.Integer(), nullable=True),
    sa.Column('legsilation_id', sa.Integer(), nullable=True),
    sa.Column('congress_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['congress_id'], ['congress.congress_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legislation_committee_id'], ['legislation_committee.legislation_committee_id'], ),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.legislation_id'], ),
    sa.ForeignKeyConstraint(['legsilation_id'], ['legislation.legislation_id'], ),
    sa.PrimaryKeyConstraint('committee_association_id')
    )
    op.create_index(op.f('ix_legislation_committee_association_congress_id'), 'legislation_committee_association', ['congress_id'], unique=False)
    op.create_index(op.f('ix_legislation_committee_association_legislation_committee_id'), 'legislation_committee_association', ['legislation_committee_id'], unique=False)
    op.create_index(op.f('ix_legislation_committee_association_legislation_id'), 'legislation_committee_association', ['legislation_id'], unique=False)
    op.create_index(op.f('ix_legislation_committee_association_legsilation_id'), 'legislation_committee_association', ['legsilation_id'], unique=False)
    op.create_table('legislation_version',
    sa.Column('legislation_version_id', sa.Integer(), nullable=False),
    sa.Column('legislation_version', sa.Enum('IS', 'IH', 'RAS', 'RAH', 'RFS', 'RFH', 'RDS', 'RHS', 'RCS', 'RCH', 'RS', 'RH', 'PCS', 'PCH', 'CPS', 'CPH', 'EAS', 'EAH', 'ES', 'EH', 'ENR', name='legislationversionenum'), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('legislation_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.legislation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('legislation_version_id')
    )
    op.create_index(op.f('ix_legislation_version_legislation_id'), 'legislation_version', ['legislation_id'], unique=False)
    op.create_index(op.f('ix_legislation_version_legislation_version'), 'legislation_version', ['legislation_version'], unique=False)
    op.create_index(op.f('ix_legislation_version_version_id'), 'legislation_version', ['version_id'], unique=False)
    op.create_index('legis_version', 'legislation_version', ['legislation_version', 'legislation_id'], unique=False)
    op.create_table('usc_chapter',
    sa.Column('usc_chapter_id', sa.Integer(), nullable=False),
    sa.Column('short_title', sa.String(), nullable=True),
    sa.Column('long_title', sa.String(), nullable=True),
    sa.Column('document', sa.String(), nullable=True),
    sa.Column('usc_ident', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('usc_release_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usc_release_id'], ['usc_release.usc_release_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usc_chapter_id')
    )
    op.create_index(op.f('ix_usc_chapter_version_id'), 'usc_chapter', ['version_id'], unique=False)
    op.create_table('usc_popular_name',
    sa.Column('usc_popular_name_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('public_law_number', sa.String(), nullable=True),
    sa.Column('act_date', sa.Date(), nullable=True),
    sa.Column('act_congress', sa.Integer(), nullable=True),
    sa.Column('usc_release_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usc_release_id'], ['usc_release.usc_release_id'], ),
    sa.PrimaryKeyConstraint('usc_popular_name_id')
    )
    op.create_index(op.f('ix_usc_popular_name_usc_release_id'), 'usc_popular_name', ['usc_release_id'], unique=False)
    op.create_table('legislation_content',
    sa.Column('legislation_content_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('lc_ident', sa.String(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('section_display', sa.String(), nullable=True),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('content_str', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('action_parse', billparser.db.models.CastingArray(JSONB), nullable=True),
    sa.Column('legislation_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['legislation_version_id'], ['legislation_version.legislation_version_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['legislation_content.legislation_content_id'], ),
    sa.PrimaryKeyConstraint('legislation_content_id')
    )
    op.create_index(op.f('ix_legislation_content_legislation_version_id'), 'legislation_content', ['legislation_version_id'], unique=False)
    op.create_table('usc_act_section',
    sa.Column('usc_act_section_id', sa.Integer(), nullable=False),
    sa.Column('act_section', sa.String(), nullable=True),
    sa.Column('usc_title', sa.String(), nullable=True),
    sa.Column('usc_section', sa.String(), nullable=True),
    sa.Column('usc_popular_name_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usc_popular_name_id'], ['usc_popular_name.usc_popular_name_id'], ),
    sa.PrimaryKeyConstraint('usc_act_section_id')
    )
    op.create_index(op.f('ix_usc_act_section_usc_popular_name_id'), 'usc_act_section', ['usc_popular_name_id'], unique=False)
    op.create_table('usc_section',
    sa.Column('usc_section_id', sa.Integer(), nullable=False),
    sa.Column('usc_ident', sa.String(), nullable=True),
    sa.Column('usc_guid', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('section_display', sa.String(), nullable=True),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('usc_chapter_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['usc_section.usc_section_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usc_chapter_id'], ['usc_chapter.usc_chapter_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usc_section_id')
    )
    op.create_index(op.f('ix_usc_section_parent_id'), 'usc_section', ['parent_id'], unique=False)
    op.create_index(op.f('ix_usc_section_usc_chapter_id'), 'usc_section', ['usc_chapter_id'], unique=False)
    op.create_index(op.f('ix_usc_section_version_id'), 'usc_section', ['version_id'], unique=False)
    op.create_table('usc_content',
    sa.Column('usc_content_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('usc_ident', sa.String(), nullable=True),
    sa.Column('usc_guid', sa.String(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('section_display', sa.String(), nullable=True),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('content_str', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('usc_section_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['usc_content.usc_content_id'], ),
    sa.ForeignKeyConstraint(['usc_section_id'], ['usc_section.usc_section_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usc_content_id')
    )
    op.create_index('content_ident', 'usc_content', ['usc_ident', 'version_id'], unique=False)
    op.create_index(op.f('ix_usc_content_parent_id'), 'usc_content', ['parent_id'], unique=False)
    op.create_index(op.f('ix_usc_content_usc_section_id'), 'usc_content', ['usc_section_id'], unique=False)
    op.create_index(op.f('ix_usc_content_version_id'), 'usc_content', ['version_id'], unique=False)
    op.create_table('usc_content_diff',
    sa.Column('usc_content_diff_id', sa.Integer(), nullable=False),
    sa.Column('usc_ident', sa.String(), nullable=True),
    sa.Column('usc_guid', sa.String(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('section_display', sa.String(), nullable=True),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('content_str', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('usc_content_id', sa.Integer(), nullable=True),
    sa.Column('usc_section_id', sa.Integer(), nullable=True),
    sa.Column('usc_chapter_id', sa.Integer(), nullable=True),
    sa.Column('legislation_content_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['legislation_content_id'], ['legislation_content.legislation_content_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usc_chapter_id'], ['usc_chapter.usc_chapter_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usc_content_id'], ['usc_content.usc_content_id'], ),
    sa.ForeignKeyConstraint(['usc_section_id'], ['usc_section.usc_section_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usc_content_diff_id')
    )
    op.create_index(op.f('ix_usc_content_diff_legislation_content_id'), 'usc_content_diff', ['legislation_content_id'], unique=False)
    op.create_index(op.f('ix_usc_content_diff_usc_chapter_id'), 'usc_content_diff', ['usc_chapter_id'], unique=False)
    op.create_index(op.f('ix_usc_content_diff_usc_content_id'), 'usc_content_diff', ['usc_content_id'], unique=False)
    op.create_index(op.f('ix_usc_content_diff_usc_section_id'), 'usc_content_diff', ['usc_section_id'], unique=False)
    op.create_index(op.f('ix_usc_content_diff_version_id'), 'usc_content_diff', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usc_content_diff_version_id'), table_name='usc_content_diff')
    op.drop_index(op.f('ix_usc_content_diff_usc_section_id'), table_name='usc_content_diff')
    op.drop_index(op.f('ix_usc_content_diff_usc_content_id'), table_name='usc_content_diff')
    op.drop_index(op.f('ix_usc_content_diff_usc_chapter_id'), table_name='usc_content_diff')
    op.drop_index(op.f('ix_usc_content_diff_legislation_content_id'), table_name='usc_content_diff')
    op.drop_table('usc_content_diff')
    op.drop_index(op.f('ix_usc_content_version_id'), table_name='usc_content')
    op.drop_index(op.f('ix_usc_content_usc_section_id'), table_name='usc_content')
    op.drop_index(op.f('ix_usc_content_parent_id'), table_name='usc_content')
    op.drop_index('content_ident', table_name='usc_content')
    op.drop_table('usc_content')
    op.drop_index(op.f('ix_usc_section_version_id'), table_name='usc_section')
    op.drop_index(op.f('ix_usc_section_usc_chapter_id'), table_name='usc_section')
    op.drop_index(op.f('ix_usc_section_parent_id'), table_name='usc_section')
    op.drop_table('usc_section')
    op.drop_index(op.f('ix_usc_act_section_usc_popular_name_id'), table_name='usc_act_section')
    op.drop_table('usc_act_section')
    op.drop_index(op.f('ix_legislation_content_legislation_version_id'), table_name='legislation_content')
    op.drop_table('legislation_content')
    op.drop_index(op.f('ix_usc_popular_name_usc_release_id'), table_name='usc_popular_name')
    op.drop_table('usc_popular_name')
    op.drop_index(op.f('ix_usc_chapter_version_id'), table_name='usc_chapter')
    op.drop_table('usc_chapter')
    op.drop_index('legis_version', table_name='legislation_version')
    op.drop_index(op.f('ix_legislation_version_version_id'), table_name='legislation_version')
    op.drop_index(op.f('ix_legislation_version_legislation_version'), table_name='legislation_version')
    op.drop_index(op.f('ix_legislation_version_legislation_id'), table_name='legislation_version')
    op.drop_table('legislation_version')
    op.drop_index(op.f('ix_legislation_committee_association_legsilation_id'), table_name='legislation_committee_association')
    op.drop_index(op.f('ix_legislation_committee_association_legislation_id'), table_name='legislation_committee_association')
    op.drop_index(op.f('ix_legislation_committee_association_legislation_committee_id'), table_name='legislation_committee_association')
    op.drop_index(op.f('ix_legislation_committee_association_congress_id'), table_name='legislation_committee_association')
    op.drop_table('legislation_committee_association')
    op.drop_table('usc_release')
    op.drop_index(op.f('ix_legislation_policy_areas'), table_name='legislation')
    op.drop_index(op.f('ix_legislation_legislative_subjects'), table_name='legislation')
    op.drop_index(op.f('ix_legislation_chamber'), table_name='legislation')
    op.drop_table('legislation')
    op.drop_index(op.f('ix_version_base_id'), table_name='version')
    op.drop_table('version')
    op.drop_index(op.f('ix_legislation_committee_subcommittee'), table_name='legislation_committee')
    op.drop_table('legislation_committee')
    op.drop_table('congress')
    # ### end Alembic commands ###
