"""Add llm query table

Revision ID: 3e1b4b7108bb
Revises: b1fe847bfdea
Create Date: 2025-02-15 02:14:19.498234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e1b4b7108bb"
down_revision: Union[str, None] = "b1fe847bfdea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_llm_query",
        sa.Column("user_llm_query_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("legislation_version_id", sa.Integer(), nullable=True),
        sa.Column("query", sa.String(), nullable=False),
        sa.Column("response", sa.String(), nullable=False),
        sa.Column("safe", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["legislation_version_id"],
            ["legislation_version.legislation_version_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["sensitive.user_ident.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_llm_query_id"),
        schema="sensitive",
    )
    op.create_index(
        op.f("ix_sensitive_user_llm_query_legislation_version_id"),
        "user_llm_query",
        ["legislation_version_id"],
        unique=False,
        schema="sensitive",
    )
    op.create_index(
        op.f("ix_sensitive_user_llm_query_query"),
        "user_llm_query",
        ["query"],
        unique=False,
        schema="sensitive",
    )
    op.create_index(
        op.f("ix_sensitive_user_llm_query_user_id"),
        "user_llm_query",
        ["user_id"],
        unique=False,
        schema="sensitive",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sensitive_user_llm_query_user_id"),
        table_name="user_llm_query",
        schema="sensitive",
    )
    op.drop_index(
        op.f("ix_sensitive_user_llm_query_query"),
        table_name="user_llm_query",
        schema="sensitive",
    )
    op.drop_index(
        op.f("ix_sensitive_user_llm_query_legislation_version_id"),
        table_name="user_llm_query",
        schema="sensitive",
    )
    op.drop_table("user_llm_query", schema="sensitive")
    # ### end Alembic commands ###
