"""bioguide_social_job

Revision ID: 45716515aad4
Revises: c9d7e37be069
Create Date: 2025-02-15 05:31:37.744644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45716515aad4'
down_revision: Union[str, None] = 'c9d7e37be069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legislator', sa.Column('job', sa.Enum('Senator', 'Representative', name='legislatorjob'), nullable=True))
    op.add_column('legislator', sa.Column('congress_id', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('legislator', sa.Column('twitter', sa.String(), nullable=True))
    op.add_column('legislator', sa.Column('facebook', sa.String(), nullable=True))
    op.add_column('legislator', sa.Column('youtube', sa.String(), nullable=True))
    op.add_column('legislator', sa.Column('instagram', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legislator', 'instagram')
    op.drop_column('legislator', 'youtube')
    op.drop_column('legislator', 'facebook')
    op.drop_column('legislator', 'twitter')
    op.drop_column('legislator', 'congress_id')
    op.drop_column('legislator', 'job')
    # ### end Alembic commands ###
