"""Legislators

Revision ID: 52bde36f1f81
Revises: 25859598b635
Create Date: 2024-01-10 21:39:26.221463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bde36f1f81'
down_revision: Union[str, None] = '25859598b635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legislator',
    sa.Column('legislator_id', sa.Integer(), nullable=False),
    sa.Column('bioguide_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('legislator_id')
    )
    op.create_index(op.f('ix_legislator_bioguide_id'), 'legislator', ['bioguide_id'], unique=True)
    op.create_index(op.f('ix_legislator_district'), 'legislator', ['district'], unique=False)
    op.create_index(op.f('ix_legislator_party'), 'legislator', ['party'], unique=False)
    op.create_index(op.f('ix_legislator_state'), 'legislator', ['state'], unique=False)
    op.create_table('legislation_sponsorship',
    sa.Column('legislation_sponsorship_id', sa.Integer(), nullable=False),
    sa.Column('legislator_bioguide_id', sa.String(), nullable=True),
    sa.Column('legislation_id', sa.Integer(), nullable=True),
    sa.Column('cosponsor', sa.Boolean(), nullable=True),
    sa.Column('original', sa.Boolean(), nullable=True),
    sa.Column('sponsorship_date', sa.Date(), nullable=True),
    sa.Column('sponsorship_withdrawn_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.legislation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legislator_bioguide_id'], ['legislator.bioguide_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('legislation_sponsorship_id')
    )
    op.create_index(op.f('ix_legislation_sponsorship_cosponsor'), 'legislation_sponsorship', ['cosponsor'], unique=False)
    op.create_index(op.f('ix_legislation_sponsorship_legislation_id'), 'legislation_sponsorship', ['legislation_id'], unique=False)
    op.create_index(op.f('ix_legislation_sponsorship_legislator_bioguide_id'), 'legislation_sponsorship', ['legislator_bioguide_id'], unique=False)
    op.create_index(op.f('ix_legislation_sponsorship_original'), 'legislation_sponsorship', ['original'], unique=False)
    op.create_index(op.f('ix_legislation_sponsorship_sponsorship_withdrawn_date'), 'legislation_sponsorship', ['sponsorship_withdrawn_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legislation_sponsorship_sponsorship_withdrawn_date'), table_name='legislation_sponsorship')
    op.drop_index(op.f('ix_legislation_sponsorship_original'), table_name='legislation_sponsorship')
    op.drop_index(op.f('ix_legislation_sponsorship_legislator_bioguide_id'), table_name='legislation_sponsorship')
    op.drop_index(op.f('ix_legislation_sponsorship_legislation_id'), table_name='legislation_sponsorship')
    op.drop_index(op.f('ix_legislation_sponsorship_cosponsor'), table_name='legislation_sponsorship')
    op.drop_table('legislation_sponsorship')
    op.drop_index(op.f('ix_legislator_state'), table_name='legislator')
    op.drop_index(op.f('ix_legislator_party'), table_name='legislator')
    op.drop_index(op.f('ix_legislator_district'), table_name='legislator')
    op.drop_index(op.f('ix_legislator_bioguide_id'), table_name='legislator')
    op.drop_table('legislator')
    # ### end Alembic commands ###
