"""votes

Revision ID: 79a29914ef4a
Revises: d01322760f6d
Create Date: 2025-01-18 20:57:35.036173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79a29914ef4a'
down_revision: Union[str, None] = 'd01322760f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legislation_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('legislation_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('independent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('republican', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('democrat', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.legislation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislation_vote_id'), 'legislation_vote', ['id'], unique=False)
    op.create_index(op.f('ix_legislation_vote_legislation_id'), 'legislation_vote', ['legislation_id'], unique=False)
    op.create_index(op.f('ix_legislation_vote_number'), 'legislation_vote', ['number'], unique=False)
    op.create_index(op.f('ix_legislation_vote_question'), 'legislation_vote', ['question'], unique=False)
    op.create_table('legislator_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislation_vote_id', sa.Integer(), nullable=True),
    sa.Column('legislator_bioguide_id', sa.String(), nullable=True),
    sa.Column('vote', sa.Enum('yay', 'nay', 'present', 'abstain', name='legislatorvotetype'), nullable=True),
    sa.ForeignKeyConstraint(['legislation_vote_id'], ['legislation_vote.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legislator_bioguide_id'], ['legislator.bioguide_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislator_vote_id'), 'legislator_vote', ['id'], unique=False)
    op.create_index(op.f('ix_legislator_vote_legislation_vote_id'), 'legislator_vote', ['legislation_vote_id'], unique=False)
    op.create_index(op.f('ix_legislator_vote_legislator_bioguide_id'), 'legislator_vote', ['legislator_bioguide_id'], unique=False)
    op.add_column('legislator', sa.Column('lis_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_legislator_lis_id'), 'legislator', ['lis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legislator_lis_id'), table_name='legislator')
    op.drop_column('legislator', 'lis_id')
    op.drop_index(op.f('ix_legislator_vote_legislator_bioguide_id'), table_name='legislator_vote')
    op.drop_index(op.f('ix_legislator_vote_legislation_vote_id'), table_name='legislator_vote')
    op.drop_index(op.f('ix_legislator_vote_id'), table_name='legislator_vote')
    op.drop_table('legislator_vote')
    op.drop_index(op.f('ix_legislation_vote_question'), table_name='legislation_vote')
    op.drop_index(op.f('ix_legislation_vote_number'), table_name='legislation_vote')
    op.drop_index(op.f('ix_legislation_vote_legislation_id'), table_name='legislation_vote')
    op.drop_index(op.f('ix_legislation_vote_id'), table_name='legislation_vote')
    op.drop_table('legislation_vote')
    # ### end Alembic commands ###
