"""Create prompt tagging table

Revision ID: aee414b2c361
Revises: 9a72e5faa767
Create Date: 2024-12-18 21:04:37.411800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aee414b2c361'
down_revision: Union[str, None] = '9a72e5faa767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legislation_content_tag',
    sa.Column('legislation_content_tag_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=True),
    sa.Column('legislation_content_id', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['legislation_content_id'], ['legislation_content.legislation_content_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.prompt.prompt_id'], ),
    sa.PrimaryKeyConstraint('legislation_content_tag_id')
    )
    op.create_index(op.f('ix_legislation_content_tag_legislation_content_id'), 'legislation_content_tag', ['legislation_content_id'], unique=False)
    op.create_index(op.f('ix_legislation_content_tag_prompt_id'), 'legislation_content_tag', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_legislation_content_tag_tags'), 'legislation_content_tag', ['tags'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legislation_content_tag_tags'), table_name='legislation_content_tag')
    op.drop_index(op.f('ix_legislation_content_tag_prompt_id'), table_name='legislation_content_tag')
    op.drop_index(op.f('ix_legislation_content_tag_legislation_content_id'), table_name='legislation_content_tag')
    op.drop_table('legislation_content_tag')
    # ### end Alembic commands ###
