"""Add congress to uniq_bill

Revision ID: af9ab9994117
Revises: bf2269ea67a1
Create Date: 2025-01-08 02:28:27.738643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af9ab9994117'
down_revision: Union[str, None] = 'bf2269ea67a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unq_bill', 'legislation', type_='unique')
    op.create_unique_constraint('unq_bill', 'legislation', ['chamber', 'number', 'legislation_type', 'congress_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unq_bill', 'legislation', type_='unique')
    op.create_unique_constraint('unq_bill', 'legislation', ['chamber', 'number', 'legislation_type'])
    # ### end Alembic commands ###
