"""cascade deletes

Revision ID: b1fe847bfdea
Revises: b3b426df69a6
Create Date: 2025-01-20 03:08:48.169451

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1fe847bfdea"
down_revision: Union[str, None] = "b3b426df69a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "legislation_action_parse_legislation_version_id_fkey",
        "legislation_action_parse",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "legislation_action_parse",
        "legislation_version",
        ["legislation_version_id"],
        ["legislation_version_id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        "ix_legislation_committee_association_legsilation_id",
        table_name="legislation_committee_association",
    )
    op.drop_constraint(
        "legislation_committee_association_legislation_committee_id_fkey",
        "legislation_committee_association",
        type_="foreignkey",
    )
    op.drop_constraint(
        "legislation_committee_association_legislation_id_fkey",
        "legislation_committee_association",
        type_="foreignkey",
    )
    op.drop_constraint(
        "legislation_committee_association_legsilation_id_fkey",
        "legislation_committee_association",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "legislation_committee_association",
        "legislation_committee",
        ["legislation_committee_id"],
        ["legislation_committee_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "legislation_committee_association",
        "legislation",
        ["legislation_id"],
        ["legislation_id"],
        ondelete="CASCADE",
    )
    op.drop_column("legislation_committee_association", "legsilation_id")
    op.create_index(
        op.f("ix_legislation_content_tag_prompt_batch_id"),
        "legislation_content_tag",
        ["prompt_batch_id"],
        unique=False,
    )
    op.drop_constraint(
        "usc_content_diff_usc_content_id_fkey", "usc_content_diff", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "usc_content_diff",
        "usc_content",
        ["usc_content_id"],
        ["usc_content_id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_appropriations_appropriation_prompt_batch_id"),
        "appropriation",
        ["prompt_batch_id"],
        unique=False,
        schema="appropriations",
    )
    op.create_index(
        op.f("ix_sensitive_user_usc_content_user_usc_content_folder_id"),
        "user_usc_content",
        ["user_usc_content_folder_id"],
        unique=False,
        schema="sensitive",
    )
    op.drop_index(
        "ix_sensitive_user_user_usc_content_folder_user_usc_cont_22f3",
        table_name="user_usc_content_folder",
        schema="sensitive",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_sensitive_user_user_usc_content_folder_user_usc_cont_22f3",
        "user_usc_content_folder",
        ["user_usc_content_folder_id"],
        unique=False,
        schema="sensitive",
    )
    op.drop_index(
        op.f("ix_sensitive_user_usc_content_user_usc_content_folder_id"),
        table_name="user_usc_content",
        schema="sensitive",
    )
    op.drop_index(
        op.f("ix_appropriations_appropriation_prompt_batch_id"),
        table_name="appropriation",
        schema="appropriations",
    )
    op.drop_constraint(None, "usc_content_diff", type_="foreignkey")
    op.create_foreign_key(
        "usc_content_diff_usc_content_id_fkey",
        "usc_content_diff",
        "usc_content",
        ["usc_content_id"],
        ["usc_content_id"],
    )
    op.drop_index(
        op.f("ix_legislation_content_tag_prompt_batch_id"),
        table_name="legislation_content_tag",
    )
    op.add_column(
        "legislation_committee_association",
        sa.Column("legsilation_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "legislation_committee_association", type_="foreignkey")
    op.drop_constraint(None, "legislation_committee_association", type_="foreignkey")
    op.create_foreign_key(
        "legislation_committee_association_legsilation_id_fkey",
        "legislation_committee_association",
        "legislation",
        ["legsilation_id"],
        ["legislation_id"],
    )
    op.create_foreign_key(
        "legislation_committee_association_legislation_id_fkey",
        "legislation_committee_association",
        "legislation",
        ["legislation_id"],
        ["legislation_id"],
    )
    op.create_foreign_key(
        "legislation_committee_association_legislation_committee_id_fkey",
        "legislation_committee_association",
        "legislation_committee",
        ["legislation_committee_id"],
        ["legislation_committee_id"],
    )
    op.create_index(
        "ix_legislation_committee_association_legsilation_id",
        "legislation_committee_association",
        ["legsilation_id"],
        unique=False,
    )
    op.drop_constraint(None, "legislation_action_parse", type_="foreignkey")
    op.create_foreign_key(
        "legislation_action_parse_legislation_version_id_fkey",
        "legislation_action_parse",
        "legislation_version",
        ["legislation_version_id"],
        ["legislation_version_id"],
    )
    # ### end Alembic commands ###
