"""add usc tracking

Revision ID: c941abf22042
Revises: d01322760f6d
Create Date: 2025-01-14 01:27:53.325329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c941abf22042"
down_revision: Union[str, None] = "d01322760f6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_usc_content_folder",
        sa.Column("user_usc_content_folder_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["sensitive.user_ident.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_usc_content_folder_id"),
        schema="sensitive",
    )
    op.create_index(
        op.f("ix_sensitive_user_usc_content_folder_user_id"),
        "user_usc_content_folder",
        ["user_id"],
        unique=False,
        schema="sensitive",
    )
    op.create_table(
        "user_usc_content",
        sa.Column("user_usc_content_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("user_usc_content_folder_id", sa.Integer(), nullable=True),
        sa.Column("usc_ident", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["sensitive.user_ident.user_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_usc_content_folder_id"],
            ["sensitive.user_usc_content_folder.user_usc_content_folder_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_usc_content_id"),
        schema="sensitive",
    )
    op.create_index(
        op.f("ix_sensitive_user_usc_content_user_id"),
        "user_usc_content",
        ["user_id"],
        unique=False,
        schema="sensitive",
    )
    op.create_index(
        op.f("ix_sensitive_user_user_usc_content_folder_user_usc_content_folder_id"),
        "user_usc_content_folder",
        ["user_usc_content_folder_id"],
        unique=False,
        schema="sensitive",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        op.f("ix_sensitive_user_usc_content_folder_user_id"),
        table_name="user_usc_content_folder",
        schema="sensitive",
    )
    op.drop_table("user_usc_content_folder", schema="sensitive")
    op.drop_index(
        op.f("ix_sensitive_user_usc_content_user_usc_content_folder_id"),
        table_name="user_usc_content",
        schema="sensitive",
    )
    op.drop_index(
        op.f("ix_sensitive_user_usc_content_user_id"),
        table_name="user_usc_content",
        schema="sensitive",
    )
    op.drop_table("user_usc_content", schema="sensitive")
    # ### end Alembic commands ###
