"""Your migration message here

Revision ID: c9d7e37be069
Revises: b1fe847bfdea
Create Date: 2025-02-15 05:17:39.648944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d7e37be069'
down_revision: Union[str, None] = 'b1fe847bfdea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('legislation_action_parse_legislation_version_id_fkey', 'legislation_action_parse', type_='foreignkey')
    op.create_foreign_key(None, 'legislation_action_parse', 'legislation_version', ['legislation_version_id'], ['legislation_version_id'], ondelete='CASCADE')
    op.drop_constraint('legislation_committee_association_legislation_committee_id_fkey', 'legislation_committee_association', type_='foreignkey')
    op.drop_constraint('legislation_committee_association_legislation_id_fkey', 'legislation_committee_association', type_='foreignkey')
    op.create_foreign_key(None, 'legislation_committee_association', 'legislation', ['legislation_id'], ['legislation_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'legislation_committee_association', 'legislation_committee', ['legislation_committee_id'], ['legislation_committee_id'], ondelete='CASCADE')
    op.drop_constraint('usc_content_diff_usc_content_id_fkey', 'usc_content_diff', type_='foreignkey')
    op.create_foreign_key(None, 'usc_content_diff', 'usc_content', ['usc_content_id'], ['usc_content_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usc_content_diff', type_='foreignkey')
    op.create_foreign_key('usc_content_diff_usc_content_id_fkey', 'usc_content_diff', 'usc_content', ['usc_content_id'], ['usc_content_id'])
    op.drop_constraint(None, 'legislation_committee_association', type_='foreignkey')
    op.drop_constraint(None, 'legislation_committee_association', type_='foreignkey')
    op.create_foreign_key('legislation_committee_association_legislation_id_fkey', 'legislation_committee_association', 'legislation', ['legislation_id'], ['legislation_id'])
    op.create_foreign_key('legislation_committee_association_legislation_committee_id_fkey', 'legislation_committee_association', 'legislation_committee', ['legislation_committee_id'], ['legislation_committee_id'])
    op.drop_constraint(None, 'legislation_action_parse', type_='foreignkey')
    op.create_foreign_key('legislation_action_parse_legislation_version_id_fkey', 'legislation_action_parse', 'legislation_version', ['legislation_version_id'], ['legislation_version_id'])
    # ### end Alembic commands ###
