"""Initial migration

Revision ID: f6488f13146c
Revises:
Create Date: 2024-12-22 02:07:35.697742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateSchema
from sqlalchemy import Text
import billparser

# revision identifiers, used by Alembic.
revision: str = 'f6488f13146c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(CreateSchema("appropriations", if_not_exists=True))
    op.execute(CreateSchema("prompts", if_not_exists=True))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('congress',
    sa.Column('congress_id', sa.Integer(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('congress_id')
    )
    op.create_table('legislation_committee',
    sa.Column('legislation_committee_id', sa.Integer(), nullable=False),
    sa.Column('system_code', sa.String(), nullable=True),
    sa.Column('chamber', sa.Enum('House', 'Senate', name='legislationchamber'), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('committee_type', sa.String(), nullable=True),
    sa.Column('subcommittee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subcommittee'], ['legislation_committee.legislation_committee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('legislation_committee_id')
    )
    op.create_index(op.f('ix_legislation_committee_subcommittee'), 'legislation_committee', ['subcommittee'], unique=False)
    op.create_table('legislator',
    sa.Column('legislator_id', sa.Integer(), nullable=False),
    sa.Column('bioguide_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('legislator_id')
    )
    op.create_index(op.f('ix_legislator_bioguide_id'), 'legislator', ['bioguide_id'], unique=True)
    op.create_index(op.f('ix_legislator_district'), 'legislator', ['district'], unique=False)
    op.create_index(op.f('ix_legislator_party'), 'legislator', ['party'], unique=False)
    op.create_index(op.f('ix_legislator_state'), 'legislator', ['state'], unique=False)
    op.create_table('prompt',
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('prompt_id'),
    schema='prompts'
    )
    op.create_table('version',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('base_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['base_id'], ['version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_version_base_id'), 'version', ['base_id'], unique=False)
    op.create_table('legislation',
    sa.Column('legislation_id', sa.Integer(), nullable=False),
    sa.Column('chamber', sa.Enum('House', 'Senate', name='legislationchamber'), nullable=True),
    sa.Column('legislation_type', sa.Enum('Bill', 'CRes', 'Res', 'JRes', name='legislationtype'), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('congress_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('policy_areas', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('legislative_subjects', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['congress_id'], ['congress.congress_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('legislation_id'),
    sa.UniqueConstraint('chamber', 'number', 'legislation_type', name='unq_bill')
    )
    op.create_index(op.f('ix_legislation_chamber'), 'legislation', ['chamber'], unique=False)
    op.create_index(op.f('ix_legislation_legislative_subjects'), 'legislation', ['legislative_subjects'], unique=False)
    op.create_index(op.f('ix_legislation_policy_areas'), 'legislation', ['policy_areas'], unique=False)
    op.create_table('legislative_policy_area',
    sa.Column('legislative_policy_area_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('congress_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['congress_id'], ['congress.congress_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('legislative_policy_area_id'),
    sa.UniqueConstraint('name', 'congress_id', name='unq_leg_pol')
    )
    op.create_index(op.f('ix_legislative_policy_area_congress_id'), 'legislative_policy_area', ['congress_id'], unique=False)
    op.create_index(op.f('ix_legislative_policy_area_name'), 'legislative_policy_area', ['name'], unique=True)
    op.create_table('legislative_subject',
    sa.Column('legislative_subject_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('congress_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['congress_id'], ['congress.congress_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('legislative_subject_id'),
    sa.UniqueConstraint('subject', 'congress_id', name='unq_leg_subj')
    )
    op.create_index(op.f('ix_legislative_subject_congress_id'), 'legislative_subject', ['congress_id'], unique=False)
    op.create_index(op.f('ix_legislative_subject_subject'), 'legislative_subject', ['subject'], unique=False)
    op.create_table('usc_release',
    sa.Column('usc_release_id', sa.Integer(), nullable=False),
    sa.Column('short_title', sa.String(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('long_title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usc_release_id')
    )
    op.create_table('legislation_committee_association',
    sa.Column('committee_association_id', sa.Integer(), nullable=False),
    sa.Column('legislation_committee_id', sa.Integer(), nullable=True),
    sa.Column('referred_date', sa.DateTime(), nullable=True),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('legislation_id', sa.Integer(), nullable=True),
    sa.Column('congress_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['congress_id'], ['congress.congress_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legislation_committee_id'], ['legislation_committee.legislation_committee_id'], ),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.legislation_id'], ),
    sa.PrimaryKeyConstraint('committee_association_id')
    )
    op.create_index(op.f('ix_legislation_committee_association_congress_id'), 'legislation_committee_association', ['congress_id'], unique=False)
    op.create_index(op.f('ix_legislation_committee_association_legislation_committee_id'), 'legislation_committee_association', ['legislation_committee_id'], unique=False)
    op.create_index(op.f('ix_legislation_committee_association_legislation_id'), 'legislation_committee_association', ['legislation_id'], unique=False)
    op.create_table('legislation_sponsorship',
    sa.Column('legislation_sponsorship_id', sa.Integer(), nullable=False),
    sa.Column('legislator_bioguide_id', sa.String(), nullable=True),
    sa.Column('legislation_id', sa.Integer(), nullable=True),
    sa.Column('cosponsor', sa.Boolean(), nullable=True),
    sa.Column('original', sa.Boolean(), nullable=True),
    sa.Column('sponsorship_date', sa.Date(), nullable=True),
    sa.Column('sponsorship_withdrawn_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.legislation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legislator_bioguide_id'], ['legislator.bioguide_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('legislation_sponsorship_id')
    )
    op.create_index(op.f('ix_legislation_sponsorship_cosponsor'), 'legislation_sponsorship', ['cosponsor'], unique=False)
    op.create_index(op.f('ix_legislation_sponsorship_legislation_id'), 'legislation_sponsorship', ['legislation_id'], unique=False)
    op.create_index(op.f('ix_legislation_sponsorship_legislator_bioguide_id'), 'legislation_sponsorship', ['legislator_bioguide_id'], unique=False)
    op.create_index(op.f('ix_legislation_sponsorship_original'), 'legislation_sponsorship', ['original'], unique=False)
    op.create_index(op.f('ix_legislation_sponsorship_sponsorship_withdrawn_date'), 'legislation_sponsorship', ['sponsorship_withdrawn_date'], unique=False)
    op.create_table('legislation_version',
    sa.Column('legislation_version_id', sa.Integer(), nullable=False),
    sa.Column('legislation_version', sa.Enum('IS', 'IH', 'RAS', 'RAH', 'RFS', 'RFH', 'RDS', 'RHS', 'RCS', 'RCH', 'RS', 'RH', 'PCS', 'PCH', 'CPS', 'CPH', 'EAS', 'EAH', 'ES', 'EH', 'ENR', name='legislationversionenum'), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('legislation_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.legislation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('legislation_version_id')
    )
    op.create_index(op.f('ix_legislation_version_legislation_id'), 'legislation_version', ['legislation_id'], unique=False)
    op.create_index(op.f('ix_legislation_version_legislation_version'), 'legislation_version', ['legislation_version'], unique=False)
    op.create_index(op.f('ix_legislation_version_version_id'), 'legislation_version', ['version_id'], unique=False)
    op.create_index('legis_version', 'legislation_version', ['legislation_version', 'legislation_id'], unique=False)
    op.create_table('legislative_policy_area_association',
    sa.Column('legislative_policy_area_association_id', sa.Integer(), nullable=False),
    sa.Column('legislative_policy_area_id', sa.Integer(), nullable=True),
    sa.Column('legislation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.legislation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legislative_policy_area_id'], ['legislative_policy_area.legislative_policy_area_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('legislative_policy_area_association_id')
    )
    op.create_index(op.f('ix_legislative_policy_area_association_legislation_id'), 'legislative_policy_area_association', ['legislation_id'], unique=False)
    op.create_index(op.f('ix_legislative_policy_area_association_legislative_policy_area_id'), 'legislative_policy_area_association', ['legislative_policy_area_id'], unique=False)
    op.create_table('legislative_subject_association',
    sa.Column('legislative_subject_association_id', sa.Integer(), nullable=False),
    sa.Column('legislative_subject_id', sa.Integer(), nullable=True),
    sa.Column('legislation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.legislation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legislative_subject_id'], ['legislative_subject.legislative_subject_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('legislative_subject_association_id')
    )
    op.create_index(op.f('ix_legislative_subject_association_legislation_id'), 'legislative_subject_association', ['legislation_id'], unique=False)
    op.create_index(op.f('ix_legislative_subject_association_legislative_subject_id'), 'legislative_subject_association', ['legislative_subject_id'], unique=False)
    op.create_table('usc_chapter',
    sa.Column('usc_chapter_id', sa.Integer(), nullable=False),
    sa.Column('short_title', sa.String(), nullable=True),
    sa.Column('long_title', sa.String(), nullable=True),
    sa.Column('document', sa.String(), nullable=True),
    sa.Column('usc_ident', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('usc_release_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usc_release_id'], ['usc_release.usc_release_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usc_chapter_id')
    )
    op.create_index(op.f('ix_usc_chapter_version_id'), 'usc_chapter', ['version_id'], unique=False)
    op.create_table('usc_popular_name',
    sa.Column('usc_popular_name_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('public_law_number', sa.String(), nullable=True),
    sa.Column('act_date', sa.Date(), nullable=True),
    sa.Column('act_congress', sa.Integer(), nullable=True),
    sa.Column('usc_release_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usc_release_id'], ['usc_release.usc_release_id'], ),
    sa.PrimaryKeyConstraint('usc_popular_name_id')
    )
    op.create_index(op.f('ix_usc_popular_name_usc_release_id'), 'usc_popular_name', ['usc_release_id'], unique=False)
    op.create_table('legislation_content',
    sa.Column('legislation_content_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('lc_ident', sa.String(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('section_display', sa.String(), nullable=True),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('content_str', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('action_parse', billparser.db.models.CastingArray(JSONB(astext_type=Text())), nullable=True),
    sa.Column('legislation_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['legislation_version_id'], ['legislation_version.legislation_version_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['legislation_content.legislation_content_id'], ),
    sa.PrimaryKeyConstraint('legislation_content_id')
    )
    op.create_index(op.f('ix_legislation_content_legislation_version_id'), 'legislation_content', ['legislation_version_id'], unique=False)
    op.create_table('prompt_batch',
    sa.Column('prompt_batch_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=True),
    sa.Column('legislation_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('attempted', sa.Integer(), nullable=False),
    sa.Column('successful', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['legislation_version_id'], ['legislation_version.legislation_version_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.prompt.prompt_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prompt_batch_id'),
    schema='prompts'
    )
    op.create_index(op.f('ix_prompts_prompt_batch_legislation_version_id'), 'prompt_batch', ['legislation_version_id'], unique=False, schema='prompts')
    op.create_index(op.f('ix_prompts_prompt_batch_prompt_id'), 'prompt_batch', ['prompt_id'], unique=False, schema='prompts')
    op.create_table('usc_act_section',
    sa.Column('usc_act_section_id', sa.Integer(), nullable=False),
    sa.Column('act_section', sa.String(), nullable=True),
    sa.Column('usc_title', sa.String(), nullable=True),
    sa.Column('usc_section', sa.String(), nullable=True),
    sa.Column('usc_popular_name_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usc_popular_name_id'], ['usc_popular_name.usc_popular_name_id'], ),
    sa.PrimaryKeyConstraint('usc_act_section_id')
    )
    op.create_index(op.f('ix_usc_act_section_usc_popular_name_id'), 'usc_act_section', ['usc_popular_name_id'], unique=False)
    op.create_table('usc_section',
    sa.Column('usc_section_id', sa.Integer(), nullable=False),
    sa.Column('usc_ident', sa.String(), nullable=True),
    sa.Column('usc_guid', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('section_display', sa.String(), nullable=True),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('usc_chapter_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['usc_section.usc_section_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usc_chapter_id'], ['usc_chapter.usc_chapter_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usc_section_id')
    )
    op.create_index(op.f('ix_usc_section_parent_id'), 'usc_section', ['parent_id'], unique=False)
    op.create_index(op.f('ix_usc_section_usc_chapter_id'), 'usc_section', ['usc_chapter_id'], unique=False)
    op.create_index(op.f('ix_usc_section_version_id'), 'usc_section', ['version_id'], unique=False)
    op.create_table('appropriation',
    sa.Column('appropriation_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('legislation_version_id', sa.Integer(), nullable=True),
    sa.Column('legislation_content_id', sa.Integer(), nullable=True),
    sa.Column('content_str_indicies', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('amount', sa.BIGINT(), nullable=True),
    sa.Column('new_spending', sa.Boolean(), nullable=False),
    sa.Column('fiscal_years', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('until_expended', sa.Boolean(), nullable=False),
    sa.Column('expiration_year', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['legislation_content_id'], ['legislation_content.legislation_content_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legislation_version_id'], ['legislation_version.legislation_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appropriation_id'),
    schema='appropriations'
    )
    op.create_index(op.f('ix_appropriations_appropriation_fiscal_years'), 'appropriation', ['fiscal_years'], unique=False, schema='appropriations')
    op.create_index(op.f('ix_appropriations_appropriation_legislation_content_id'), 'appropriation', ['legislation_content_id'], unique=False, schema='appropriations')
    op.create_index(op.f('ix_appropriations_appropriation_legislation_version_id'), 'appropriation', ['legislation_version_id'], unique=False, schema='appropriations')
    op.create_table('legislation_content_tag',
    sa.Column('legislation_content_tag_id', sa.Integer(), nullable=False),
    sa.Column('prompt_batch_id', sa.Integer(), nullable=True),
    sa.Column('legislation_content_id', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['legislation_content_id'], ['legislation_content.legislation_content_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_batch_id'], ['prompts.prompt_batch.prompt_batch_id'], ),
    sa.PrimaryKeyConstraint('legislation_content_tag_id')
    )
    op.create_index(op.f('ix_legislation_content_tag_legislation_content_id'), 'legislation_content_tag', ['legislation_content_id'], unique=False)
    op.create_index(op.f('ix_legislation_content_tag_prompt_batch_id'), 'legislation_content_tag', ['prompt_batch_id'], unique=False)
    op.create_index(op.f('ix_legislation_content_tag_tags'), 'legislation_content_tag', ['tags'], unique=False)
    op.create_table('usc_content',
    sa.Column('usc_content_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('usc_ident', sa.String(), nullable=True),
    sa.Column('usc_guid', sa.String(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('section_display', sa.String(), nullable=True),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('content_str', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('usc_section_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['usc_content.usc_content_id'], ),
    sa.ForeignKeyConstraint(['usc_section_id'], ['usc_section.usc_section_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usc_content_id')
    )
    op.create_index('content_ident', 'usc_content', ['usc_ident', 'version_id'], unique=False)
    op.create_index(op.f('ix_usc_content_parent_id'), 'usc_content', ['parent_id'], unique=False)
    op.create_index(op.f('ix_usc_content_usc_section_id'), 'usc_content', ['usc_section_id'], unique=False)
    op.create_index(op.f('ix_usc_content_version_id'), 'usc_content', ['version_id'], unique=False)
    op.create_table('usc_content_diff',
    sa.Column('usc_content_diff_id', sa.Integer(), nullable=False),
    sa.Column('usc_ident', sa.String(), nullable=True),
    sa.Column('usc_guid', sa.String(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('section_display', sa.String(), nullable=True),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('content_str', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('usc_content_id', sa.Integer(), nullable=True),
    sa.Column('usc_section_id', sa.Integer(), nullable=True),
    sa.Column('usc_chapter_id', sa.Integer(), nullable=True),
    sa.Column('legislation_content_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['legislation_content_id'], ['legislation_content.legislation_content_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usc_chapter_id'], ['usc_chapter.usc_chapter_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usc_content_id'], ['usc_content.usc_content_id'], ),
    sa.ForeignKeyConstraint(['usc_section_id'], ['usc_section.usc_section_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usc_content_diff_id')
    )
    op.create_index(op.f('ix_usc_content_diff_legislation_content_id'), 'usc_content_diff', ['legislation_content_id'], unique=False)
    op.create_index(op.f('ix_usc_content_diff_usc_chapter_id'), 'usc_content_diff', ['usc_chapter_id'], unique=False)
    op.create_index(op.f('ix_usc_content_diff_usc_content_id'), 'usc_content_diff', ['usc_content_id'], unique=False)
    op.create_index(op.f('ix_usc_content_diff_usc_section_id'), 'usc_content_diff', ['usc_section_id'], unique=False)
    op.create_index(op.f('ix_usc_content_diff_version_id'), 'usc_content_diff', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usc_content_diff_version_id'), table_name='usc_content_diff')
    op.drop_index(op.f('ix_usc_content_diff_usc_section_id'), table_name='usc_content_diff')
    op.drop_index(op.f('ix_usc_content_diff_usc_content_id'), table_name='usc_content_diff')
    op.drop_index(op.f('ix_usc_content_diff_usc_chapter_id'), table_name='usc_content_diff')
    op.drop_index(op.f('ix_usc_content_diff_legislation_content_id'), table_name='usc_content_diff')
    op.drop_table('usc_content_diff')
    op.drop_index(op.f('ix_usc_content_version_id'), table_name='usc_content')
    op.drop_index(op.f('ix_usc_content_usc_section_id'), table_name='usc_content')
    op.drop_index(op.f('ix_usc_content_parent_id'), table_name='usc_content')
    op.drop_index('content_ident', table_name='usc_content')
    op.drop_table('usc_content')
    op.drop_index(op.f('ix_legislation_content_tag_tags'), table_name='legislation_content_tag')
    op.drop_index(op.f('ix_legislation_content_tag_prompt_batch_id'), table_name='legislation_content_tag')
    op.drop_index(op.f('ix_legislation_content_tag_legislation_content_id'), table_name='legislation_content_tag')
    op.drop_table('legislation_content_tag')
    op.drop_index(op.f('ix_appropriations_appropriation_legislation_version_id'), table_name='appropriation', schema='appropriations')
    op.drop_index(op.f('ix_appropriations_appropriation_legislation_content_id'), table_name='appropriation', schema='appropriations')
    op.drop_index(op.f('ix_appropriations_appropriation_fiscal_years'), table_name='appropriation', schema='appropriations')
    op.drop_table('appropriation', schema='appropriations')
    op.drop_index(op.f('ix_usc_section_version_id'), table_name='usc_section')
    op.drop_index(op.f('ix_usc_section_usc_chapter_id'), table_name='usc_section')
    op.drop_index(op.f('ix_usc_section_parent_id'), table_name='usc_section')
    op.drop_table('usc_section')
    op.drop_index(op.f('ix_usc_act_section_usc_popular_name_id'), table_name='usc_act_section')
    op.drop_table('usc_act_section')
    op.drop_index(op.f('ix_prompts_prompt_batch_prompt_id'), table_name='prompt_batch', schema='prompts')
    op.drop_index(op.f('ix_prompts_prompt_batch_legislation_version_id'), table_name='prompt_batch', schema='prompts')
    op.drop_table('prompt_batch', schema='prompts')
    op.drop_index(op.f('ix_legislation_content_legislation_version_id'), table_name='legislation_content')
    op.drop_table('legislation_content')
    op.drop_index(op.f('ix_usc_popular_name_usc_release_id'), table_name='usc_popular_name')
    op.drop_table('usc_popular_name')
    op.drop_index(op.f('ix_usc_chapter_version_id'), table_name='usc_chapter')
    op.drop_table('usc_chapter')
    op.drop_index(op.f('ix_legislative_subject_association_legislative_subject_id'), table_name='legislative_subject_association')
    op.drop_index(op.f('ix_legislative_subject_association_legislation_id'), table_name='legislative_subject_association')
    op.drop_table('legislative_subject_association')
    op.drop_index(op.f('ix_legislative_policy_area_association_legislative_policy_area_id'), table_name='legislative_policy_area_association')
    op.drop_index(op.f('ix_legislative_policy_area_association_legislation_id'), table_name='legislative_policy_area_association')
    op.drop_table('legislative_policy_area_association')
    op.drop_index('legis_version', table_name='legislation_version')
    op.drop_index(op.f('ix_legislation_version_version_id'), table_name='legislation_version')
    op.drop_index(op.f('ix_legislation_version_legislation_version'), table_name='legislation_version')
    op.drop_index(op.f('ix_legislation_version_legislation_id'), table_name='legislation_version')
    op.drop_table('legislation_version')
    op.drop_index(op.f('ix_legislation_sponsorship_sponsorship_withdrawn_date'), table_name='legislation_sponsorship')
    op.drop_index(op.f('ix_legislation_sponsorship_original'), table_name='legislation_sponsorship')
    op.drop_index(op.f('ix_legislation_sponsorship_legislator_bioguide_id'), table_name='legislation_sponsorship')
    op.drop_index(op.f('ix_legislation_sponsorship_legislation_id'), table_name='legislation_sponsorship')
    op.drop_index(op.f('ix_legislation_sponsorship_cosponsor'), table_name='legislation_sponsorship')
    op.drop_table('legislation_sponsorship')
    op.drop_index(op.f('ix_legislation_committee_association_legislation_id'), table_name='legislation_committee_association')
    op.drop_index(op.f('ix_legislation_committee_association_legislation_committee_id'), table_name='legislation_committee_association')
    op.drop_index(op.f('ix_legislation_committee_association_congress_id'), table_name='legislation_committee_association')
    op.drop_table('legislation_committee_association')
    op.drop_table('usc_release')
    op.drop_index(op.f('ix_legislative_subject_subject'), table_name='legislative_subject')
    op.drop_index(op.f('ix_legislative_subject_congress_id'), table_name='legislative_subject')
    op.drop_table('legislative_subject')
    op.drop_index(op.f('ix_legislative_policy_area_name'), table_name='legislative_policy_area')
    op.drop_index(op.f('ix_legislative_policy_area_congress_id'), table_name='legislative_policy_area')
    op.drop_table('legislative_policy_area')
    op.drop_index(op.f('ix_legislation_policy_areas'), table_name='legislation')
    op.drop_index(op.f('ix_legislation_legislative_subjects'), table_name='legislation')
    op.drop_index(op.f('ix_legislation_chamber'), table_name='legislation')
    op.drop_table('legislation')
    op.drop_index(op.f('ix_version_base_id'), table_name='version')
    op.drop_table('version')
    op.drop_table('prompt', schema='prompts')
    op.drop_index(op.f('ix_legislator_state'), table_name='legislator')
    op.drop_index(op.f('ix_legislator_party'), table_name='legislator')
    op.drop_index(op.f('ix_legislator_district'), table_name='legislator')
    op.drop_index(op.f('ix_legislator_bioguide_id'), table_name='legislator')
    op.drop_table('legislator')
    op.drop_index(op.f('ix_legislation_committee_subcommittee'), table_name='legislation_committee')
    op.drop_table('legislation_committee')
    op.drop_table('congress')
    # ### end Alembic commands ###
