version: '3'
services:
  parser_api:
    container_name: congress_parser_api
    tty: true
    stdin_open: true
    environment:
    - STAGE=dev
    - PORT=9090
    - db_host=congress_postgres:5432
    - db_user=parser
    - db_pass=parser
    - db_table=us_code
    build:
      context: ../backend
      dockerfile: .docker/Dockerfile
    volumes:
    - ../backend:/usr/src/app/
    ports:
    - "9090:9090"
    depends_on:
      - congress_postgres
    networks:
      parser:
    entrypoint: "python3"
    command:
    - "-m"
    - "billparser"
  viewer_app:
    container_name: congress_viewer_app
    tty: true
    stdin_open: true
    environment:
    - STAGE=dev
    - CHOKIDAR_USEPOLLING=true
    build:
      context: ../frontend
      dockerfile: .docker/Dockerfile
    volumes:
    - ../frontend/public:/usr/src/app/public
    - ../frontend/src:/usr/src/app/src
    ports:
    - "80:3000"
    networks:
      parser:
    command:
    - "start.sh"
  # nginx:
  #   image: nginx
  #   ports:
  #     - 80:80
  #     - 443:443
  #   networks:
  #     parser:
  #   volumes:
  #     - /etc/letsencrypt:/etc/letsencrypt
  #     - ./nginx/:/etc/nginx/sites-enabled/
  congress_postgres:
    image: postgres:10.6
    container_name: congress_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: parser
      POSTGRES_USER: parser
      POSTGRES_DB: us_code
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      parser:
networks:
  parser:
    external:
      name: docker_parser
volumes:
  postgres-volume: