version: '3'
services:
  congress_parser_api:
    image: congress_parser_api:latest
    container_name: congress_parser_api
    tty: true
    stdin_open: true
    environment:
    - STAGE=dev
    - PORT=9090
    - db_host=congress_postgres:5432
    - db_user=parser
    - db_pass=parser
    - db_table=us_code
    build:
      context: ../backend
      dockerfile: .docker/Dockerfile
    volumes:
    - ../backend:/usr/src/app/
    ports:
    - "9090:9090"
    depends_on:
      - congress_postgres
    networks:
      parser:
    entrypoint: "python3"
    command:
    - "-m"
    - "congress_api"
  congress_viewer_app:
    image: congress_viewer_app:latest
    container_name: congress_viewer_app
    tty: true
    stdin_open: true
    environment:
    - STAGE=dev
    - CHOKIDAR_USEPOLLING=true
    - REACT_APP_API_URL=http://localhost:9090
    build:
      context: ../frontend
      dockerfile: .docker/Dockerfile
    volumes:
    - ../frontend/public:/usr/src/app/public
    - ../frontend/src:/usr/src/app/src
    - ../frontend/package.json:/usr/src/app/package.json
    ports:
    - "3000:3000"
    networks:
      parser:
    command:
    - "start.sh"
  congress_postgres:
    image: postgres:10.6
    container_name: congress_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: parser
      POSTGRES_USER: parser
      POSTGRES_DB: us_code
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      parser:
networks:
  parser:
    external:
      name: docker_parser
volumes:
  postgres-volume:
