version: '3'
services:
  congress_parser_api:
    container_name: beta_congress_parser_api
    environment:
    - STAGE=prod
    - db_host=10.0.0.248:5432
    - db_table=us_code_beta
    ports:
    - "9091:9090"
  congress_viewer_app:
    container_name: beta_congress_viewer_app
    volumes:
    - /var/www/congress-beta:/usr/src/app/build
    entrypoint:
    - "yarn"
    command:
    - "build"
  congress_postgres:
    container_name: beta_congress_postgres
    image: tianon/true
networks:
  parser:
    external:
      name: docker_parser
