version: "3"
services:
  viewer_app:
    tty: true
    stdin_open: true
    environment:
    - STAGE=dev
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    volumes:
    - ../:/usr/src/app
    ports:
    - "80:3000"
    networks:
      parser:
    entrypoint:
    - "yarn"
    - "start"
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      parser:
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/:/etc/nginx/sites-enabled/
networks:
  parser:
    external:
      name: docker_parser