version: '3'
services:
  parser_api:
    tty: true
    stdin_open: true
    environment:
    - STAGE=dev
    - PORT=9090
    - db_host=10.0.0.174:5432
    - db_user=parser
    - db_pass=parser
    - db_table=us_code
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    network_mode: "host"
    volumes:
    - ../:/usr/src/app/
    ports:
    - "9090:9090"
    entrypoint:
      - "bash"
volumes:
  parser-pg-data:
    driver: local